export enum AppleNotificationType {
  INITIAL_BUY = 'INITIAL_BUY',
  DID_RENEW = 'DID_RENEW',
  DID_FAIL_TO_RENEW = 'DID_FAIL_TO_RENEW',
  CANCEL = 'CANCEL',
  EXPIRED = 'EXPIRED',
  DID_CHANGE_RENEWAL_STATUS = 'DID_CHANGE_RENEWAL_STATUS',
  REFUND = 'REFUND',
  INTERACTIVE_RENEWAL = 'INTERACTIVE_RENEWAL',
  REVOKE = 'REVOKE',
}

export enum AppleNotificationSubtype {
  NONE = 'NONE',
  AUTO_RENEW_ENABLED = 'AUTO_RENEW_ENABLED',
  AUTO_RENEW_DISABLED = 'AUTO_RENEW_DISABLED',
  VOLUNTARY = 'VOLUNTARY',
  BILLING_RECOVERY = 'BILLING_RECOVERY',
  PRICE_INCREASE_CONSENT = 'PRICE_INCREASE_CONSENT',
  GRACE_PERIOD = 'GRACE_PERIOD',
}
