export const Roles = {
  ADMIN: 'admin',
  USER: 'user',
  SUB_ADMIN: 'sub_admin',
  STAFF: 'staff',
  GUEST: 'guest',
  BUSINESS_PROFILE: 'business_profile',
  SUPER_ADMIN: 'Super Admin',
};

export const Actions = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  ALL: 'all',
  // RESTORE: 'restore',
  // SOFT_DELETE: 'soft_delete',
  // READ_ALL: 'read_all',
  // UPDATE_ALL: 'update_all',
  // DELETE_ALL: 'delete_all',
  // RESTORE_ALL: 'restore_all',
  // SOFT_DELETE_ALL: 'soft_delete_all',
  // READ_OWN: 'read_own',
  // UPDATE_OWN: 'update_own',
  // DELETE_OWN: 'delete_own',
  // RESTORE_OWN: 'restore_own',
  // SOFT_DELETE_OWN: 'soft_delete_own',
};

export const ResourceTypes = {
  USERS: 'users',
  ROLES: 'roles',
  PERMISSIONS: 'permissions',
  REFERRALS: 'referrals',
  OTPS: 'otps',
  AUTH: 'auth',
  CATEGORIES: 'categories',
  PRODUCTS: 'products',
  ORDERS: 'orders',
  PAYMENTS: 'payments',
  SHIPPING: 'shipping',
  SETTINGS: 'settings',
  MESSAGES: 'messages',
  NOTIFICATIONS: 'notifications',
  REVIEWS: 'reviews',
  REPORTS: 'reports',
  BANNERS: 'banners',
  PAGES: 'pages',
  FAQS: 'faqs',
  COUPONS: 'coupons',
  BRANDS: 'brands',
  WISHLISTS: 'wishlists',
  CARTS: 'carts',
  LOCATIONS: 'locations',
  TAXES: 'taxes',
  ADDRESSES: 'addresses',
  // PAYMENT_METHODS: 'payment_methods',
  // SHIPPING_METHODS: 'shipping_methods',
  // ORDER_STATUSES: 'order_statuses',
  // ORDER_TRACKINGS: 'order_trackings',
  // ORDER_REFUNDS: 'order_refunds',
  // ORDER_PAYMENTS: 'order_payments',
  // ORDER_ITEMS: 'order_items',
  // ORDER_INVOICES: 'order_invoices',
  // ORDER_DETAILS: 'order_details',
  // ORDER_DELIVERIES: 'order_deliveries',
  // ORDER_COMMISSIONS: 'order_commissions',
};
