export const ProfileStatus = {
  INITIATED: 0, //->Business User Created
  EMAIL_VERIFIED: 1,
  MULTIPLE_BUSINESS_STATUS:2,
  INDUSTRY_ADDED: 3, //-> Business Industry Added
  CATEGORY_ADDED: 4, //-> Business Category Added
  BUSINESS_CREATED: 5, //-> Business Created

};
export const ScalabilityFactor = {
  SINGLE: 0,
  MULTIPLE: 1,
  ORGANISATION: 2,
};

// export const OutletTypesByCategory = {
//   [OutletCategoryList.FOOD_BEVERAGE]: [
//     'Restaurant',
//     'Fine Dining',
//     'Casual Dining',
//     'Buffet',
//     'Theme Restaurant',
//     'Café',
//     'Bakery',
//     'Confectionery',
//     'Ice Cream Parlour',
//     'Juice Bar',
//     'Bar',
//     'Pub',
//     'Club',
//     'Lounge',
//   ],
//   [OutletCategoryList.MOBILE_TEMPORARY]: [
//     'Food Truck',
//     'Food Stall',
//     'Food Cart',
//     'Mobile Bar',
//     'Event Pop-Up',
//     'Roaming Pop-Up',
//     'Festival Stall',
//     'Catering Service',
//     'Cloud Kitchen',
//     'Dark Kitchen',
//   ],
//   [OutletCategoryList.RETAIL_DISTRIBUTION]: [
//     'Supermarket',
//     'Convenience Store',
//     'Vending Machine',
//     'Warehouse',
//     'Distribution Outlet',
//     'Wholesale Outlet',
//     'Franchise Outlet',
//     'Commission Outlet',
//   ],
//   [OutletCategoryList.HYBRID_EXPERIMENTAL]: [
//     'Food Theater',
//     'Micro Market',
//     'Smart Vending',
//     'Hotel Restaurant',
//     'Canteen',
//     'Tasting Room',
//     'Private Dining',
//     'Interactive Dining',
//   ],
//   [OutletCategoryList.ONLINE_HOME_BASED]: [
//     'Online Only',
//     'Delivery-Based',
//     'Ghost Kitchen',
//     'Virtual Restaurant',
//     'Home-Based Business',
//     'Home Chef',
//     'Instagram-Only Business',
//   ],
// };

export const BusinessUserCreatorType = {
  ADMIN: 'Admin',
  BUSINESS: 'Business',
  SYSTEM: 'System',
  SELF: 'Self',
};
export const BusinessCreatorType = {
  ADMIN: 'Admin',
  BUSINESS_USER: 'BusinessUser',
};

export const BusinessIndustries = {
  'Retail & E-commerce': [
    'Supermarkets & Grocery Stores',
    'Fashion & Apparel',
    'Electronics & Gadgets',
    'Home & Kitchen',
    'Beauty & Personal Care',
    'Automotive Parts & Accessories',
    'Books & Stationery',
    'Furniture & Home Decor',
    'Sports & Fitness Equipment',
    'Online Marketplaces',
  ],
  'Food & Beverage': [
    'Restaurants & Cafés',
    'Fast Food Chains',
    'Bakeries & Confectioneries',
    'Catering Services',
    'Bars & Nightclubs',
    'Food Trucks',
    'Organic & Health Food Stores',
    'Beverage Production (Coffee, Tea, Soft Drinks, etc.)',
    'Wine & Liquor Stores',
    'Cloud Kitchens',
  ],
  'Health & Wellness': [
    'Hospitals & Clinics',
    'Pharmaceuticals & Drugstores',
    'Medical Devices & Equipment',
    'Health Tech & Telemedicine',
    'Fitness Centers & Gyms',
    'Spas & Wellness Centers',
    'Alternative Medicine (Ayurveda, Homeopathy, etc.)',
    'Mental Health & Counseling',
    'Senior Care & Assisted Living',
  ],
  'Finance & Insurance': [
    'Banks & Financial Institutions',
    'Investment & Wealth Management',
    'Insurance Companies',
    'Accounting & Bookkeeping Services',
    'FinTech & Payment Solutions',
    'Tax Consulting',
  ],
  'Technology & Software': [
    'Software Development',
    'IT Services & Consulting',
    'Cybersecurity Solutions',
    'AI & Machine Learning',
    'Blockchain & Cryptocurrency',
    'Cloud Computing & Data Centers',
    'SaaS & Enterprise Solutions',
  ],
  'Real Estate & Construction': [
    'Residential & Commercial Real Estate',
    'Property Management',
    'Architecture & Interior Design',
    'Construction Companies',
    'Smart Home Solutions',
    'Industrial Infrastructure',
  ],
  'Automotive & Transportation': [
    'Car Dealerships',
    'Auto Repair & Maintenance',
    'Car Rentals & Leasing',
    'Public Transportation Services',
    'Ride-Hailing & Taxi Services',
    'Logistics & Supply Chain',
    'Courier & Delivery Services',
    'EV & Automotive Innovation',
  ],
  'Education & Training': [
    'Schools & Universities',
    'E-Learning Platforms',
    'Corporate Training & Skill Development',
    'Coaching Centers & Tutoring',
    'Vocational Training',
  ],
  'Manufacturing & Industrial': [
    'Textile & Apparel Manufacturing',
    'Electronics Manufacturing',
    'Heavy Machinery',
    'Chemical & Pharmaceuticals',
    'Metal & Mining',
    'Renewable Energy Manufacturing',
  ],
  'Media & Entertainment': [
    'Film & Television Production',
    'Music & Audio Production',
    'Advertising & Marketing Agencies',
    'Video Game Development',
    'Publishing & News Media',
    'Event Planning & Management',
  ],
  'Tourism & Hospitality': [
    'Hotels & Resorts',
    'Travel Agencies',
    'Airlines & Cruise Lines',
    'Adventure & Eco-Tourism',
    'Theme Parks & Attractions',
  ],
  'Agriculture & Farming': [
    'Crop Farming',
    'Dairy & Livestock',
    'Fisheries & Aquaculture',
    'AgroTech & Precision Farming',
  ],
  'Legal & Consulting': [
    'Law Firms',
    'Business Consulting',
    'HR & Recruitment',
    'Market Research',
  ],
  'Energy & Utilities': [
    'Renewable Energy Solutions',
    'Oil & Gas',
    'Water & Waste Management',
  ],
  'Non-Profit & Social Enterprises': [
    'Charities & NGOs',
    'Social Impact Startups',
    'Environmental Conservation',
  ],
};

export const BusinessCountries = {
  USA: { name: 'USA', phoneCode: '+1', currency: 'USD' },
  Canada: { name: 'Canada', phoneCode: '+1', currency: 'CAD' },
  UK: { name: 'UK', phoneCode: '+44', currency: 'GBP' },
  Germany: { name: 'Germany', phoneCode: '+49', currency: 'EUR' },
  France: { name: 'France', phoneCode: '+33', currency: 'EUR' },
  China: { name: 'China', phoneCode: '+86', currency: 'CNY' },
  Japan: { name: 'Japan', phoneCode: '+81', currency: 'JPY' },
  Australia: { name: 'Australia', phoneCode: '+61', currency: 'AUD' },
  India: { name: 'India', phoneCode: '+91', currency: 'INR' },
  Nigeria: { name: 'Nigeria', phoneCode: '+234', currency: 'NGN' },
  Mexico: { name: 'Mexico', phoneCode: '+52', currency: 'MXN' },
  Russia: { name: 'Russia', phoneCode: '+7', currency: 'RUB' },
  Argentina: { name: 'Argentina', phoneCode: '+54', currency: 'ARS' },
  Brazil: { name: 'Brazil', phoneCode: '+55', currency: 'BRL' },
  Chile: { name: 'Chile', phoneCode: '+56', currency: 'CLP' },
  Colombia: { name: 'Colombia', phoneCode: '+57', currency: 'COP' },
  Peru: { name: 'Peru', phoneCode: '+51', currency: 'PEN' },
  Ecuador: { name: 'Ecuador', phoneCode: '+593', currency: 'USD' },
  Bolivia: { name: 'Bolivia', phoneCode: '+591', currency: 'BOB' },
  Paraguay: { name: 'Paraguay', phoneCode: '+595', currency: 'PYG' },
  Uruguay: { name: 'Uruguay', phoneCode: '+598', currency: 'UYU' },
  Venezuela: { name: 'Venezuela', phoneCode: '+58', currency: 'VES' },
  CostaRica: { name: 'Costa Rica', phoneCode: '+506', currency: 'CRC' },
  DominicanRepublic: {
    name: 'Dominican Republic',
    phoneCode: '+1',
    currency: 'DOP',
  },
  Panama: { name: 'Panama', phoneCode: '+507', currency: 'PAB' },
  SouthAfrica: { name: 'South Africa', phoneCode: '+27', currency: 'ZAR' },
  UAE: { name: 'United Arab Emirates', phoneCode: '+971', currency: 'AED' },
};

export const BusinessDocumentTypes = {
  USA: {
    'Sole Proprietorship': ['EIN', 'DBA Certificate'],
    Partnership: [
      'Partnership Agreement',
      'EIN',
      'State Registration Certificate',
    ],
    LLC: ['Articles of Organization', 'Operating Agreement', 'EIN'],
    'Private Corporation (Inc.)': [
      'Articles of Incorporation',
      'Corporate Bylaws',
      'EIN',
    ],
    'Public Corporation': ['SEC Registration', 'Articles of Incorporation'],
    'Non-Profit': ['501(c)(3) Certification', 'Articles of Incorporation'],
    Cooperative: ['Cooperative Bylaws', 'State Registration'],
    'Government-Owned Enterprise': [
      'Federal or State Charter',
      'Appropriate Regulatory Approval',
    ],
  },
  Canada: {
    'Sole Proprietorship': [
      'Business Name Registration',
      'BN (Business Number)',
    ],
    Partnership: ['Partnership Agreement', 'BN'],
    Corporation: ['Articles of Incorporation', 'Corporate Bylaws', 'BN'],
    'Non-Profit': ['CRA Non-Profit Registration', 'Articles of Incorporation'],
  },
  UK: {
    'Sole Trader': ['HMRC Registration', 'UTR (Unique Taxpayer Reference)'],
    Partnership: ['Partnership Agreement', 'HMRC Registration'],
    'Limited Company': [
      'Certificate of Incorporation',
      'Companies House Registration',
    ],
    'Public Limited Company (PLC)': [
      'Companies House Registration',
      'Stock Exchange Listing (if applicable)',
    ],
    'Charity/Non-Profit': ['Charity Commission Registration'],
    Cooperative: ['Financial Conduct Authority (FCA) Registration'],
  },
  Germany: {
    'Sole Proprietorship': [
      'Trade License (Gewerbeschein)',
      'Tax Registration (Steuernummer)',
    ],
    Partnership: ['Partnership Agreement', 'Trade License'],
    'GmbH (LLC)': [
      'Handelsregister (Commercial Register) Entry',
      'Gewerbeanmeldung (Trade Registration)',
    ],
    'AG (Public Corporation)': [
      'Stock Exchange Listing',
      'Corporate Governance Documents',
    ],
    'Non-Profit': ['NGO Registration', 'Tax-Exempt Status Certification'],
    Cooperative: ['Genossenschaftsregister (Cooperative Register) Entry'],
  },
  France: {
    'Auto-Entrepreneur': ['INSEE Registration', 'SIRET Number'],
    'SARL (LLC)': ['Articles of Association', 'Kbis Extract'],
    'SA (Corporation)': ['Statutes', 'Commercial Register Entry'],
    'Non-Profit': ['Prefecture Registration', 'Association Charter'],
    Cooperative: ['Cooperative Society Registration'],
  },
  China: {
    'Sole Proprietorship': ['Business License', 'Tax Registration Certificate'],
    Partnership: ['Business License', 'Partnership Agreement'],
    LLC: ['Business License', 'Articles of Association'],
    'State-Owned Enterprise (SOE)': [
      'Approval from SASAC (State-owned Assets Supervision and Administration Commission)',
    ],
    'Non-Profit': ['Ministry of Civil Affairs Registration'],
  },
  Japan: {
    'Sole Proprietorship': [
      'Tax Office Registration',
      'Business Registration Certificate',
    ],
    LLC: ['Articles of Incorporation', 'Company Seal Registration'],
    Corporation: [
      'Commercial Registry Registration',
      'Articles of Incorporation',
    ],
    'Non-Profit': ['Public Interest Corporation Registration'],
  },
  'South Africa': {
    'Sole Proprietorship': ['CIPC Registration', 'Tax Clearance Certificate'],
    'Private Company (Pty Ltd)': [
      'CIPC Registration',
      'MOI (Memorandum of Incorporation)',
    ],
    'Public Company (Ltd)': [
      'JSE Listing (if applicable)',
      'CIPC Registration',
    ],
    'Non-Profit': [
      'NPC Registration',
      'Public Benefit Organization (PBO) Certificate',
    ],
  },
  'United Arab Emirates': {
    'Sole Proprietorship': [
      'Trade License',
      'VAT Registration (if applicable)',
    ],
    LLC: ['Trade License', 'Memorandum of Association'],
    'Free Zone Company': ['Free Zone License', 'Shareholder Agreement'],
    'Government-Owned Business': ['Royal Decree or Government Approval'],
  },
  Australia: {
    'Sole Trader': [
      'ABN (Australian Business Number)',
      'TFN (Tax File Number)',
    ],
    Partnership: ['ABN', 'Partnership Agreement'],
    Company: [
      'ACN (Australian Company Number)',
      'ASIC Registration',
      'Constitution Document',
    ],
    Cooperative: ['State-Based Cooperative Registration'],
    Charity: ['ACNC Registration', 'Tax-Exempt Status Certification'],
  },
  India: {
    'Sole Proprietorship': [
      'GST Registration',
      'Shop & Establishment Certificate',
    ],
    Partnership: ['Partnership Deed', 'PAN', 'GST Registration'],
    LLP: ['LLP Agreement', 'Incorporation Certificate'],
    'Private Limited': ['Certificate of Incorporation', 'MOA & AOA'],
    'Public Limited': ['Certificate of Incorporation', 'SEBI Registration'],
    'Non-Profit (NGO, Trust, Society)': [
      'Trust Deed',
      '80G/12A Certification',
      'FCRA Approval',
    ],
    Cooperative: ['Registrar of Cooperative Societies Registration'],
  },
  Nigeria: {
    'Sole Proprietorship': [
      'CAC Registration',
      'Tax Identification Number (TIN)',
    ],
    Partnership: ['Partnership Agreement', 'CAC Registration'],
    'Limited Liability Company (LLC)': [
      'CAC Certificate',
      'Tax Identification Number',
    ],
    'Public Limited Company (PLC)': [
      'CAC Registration',
      'Stock Exchange Listing (if applicable)',
    ],
    'Non-Profit': ['Incorporation with CAC', 'Tax Exemption Certificate'],
  },
  Mexico: {
    'Sole Proprietorship': ['RFC Registration', 'SAT Tax Registration'],
    Partnership: ['RFC Registration', 'Partnership Agreement'],
    Corporation: ['Notarized Articles of Incorporation', 'RFC Registration'],
    Cooperative: ['Cooperative Society Registration', 'RFC'],
  },
  Russia: {
    'Sole Proprietorship': [
      'OGRNIP Registration',
      'Taxpayer Identification Number (INN)',
    ],
    LLC: ['OGRN Registration', 'Charter Documents'],
    Corporation: ['Stock Exchange Listing', 'Corporate Charter'],
    'Non-Profit': [
      'Ministry of Justice Registration',
      'Tax-Exempt Certification',
    ],
  },
  Argentina: {
    'Sole Proprietorship': ['CUIT Registration', 'AFIP Tax Registration'],
    Partnership: ['Partnership Agreement', 'CUIT Registration'],
    'SRL (LLC)': ['Articles of Incorporation', 'CUIT', 'AFIP Registration'],
    'SA (Corporation)': ['Articles of Incorporation', 'CNV Registration'],
    Cooperative: ['INAES Registration'],
    'Non-Profit': ['IGJ Registration', 'Tax-Exempt Certificate'],
  },
  Brazil: {
    'Sole Proprietorship': ['MEI Registration', 'CNPJ Number'],
    Partnership: ['Partnership Agreement', 'CNPJ'],
    'LTDA (LLC)': ['Articles of Incorporation', 'CNPJ'],
    'S.A. (Corporation)': ['Commercial Registry Entry', 'CNPJ'],
    Cooperative: ['OCB Registration'],
    'Non-Profit': ['Public Utility Status', 'CNPJ'],
  },
  Chile: {
    'Sole Proprietorship': ['RUT Registration', 'SII Tax Identification'],
    Partnership: ['RUT Registration', 'Partnership Agreement'],
    'EIRL (Single-Person LLC)': ['Company Registration', 'RUT'],
    'SpA (Corporation)': ['Articles of Incorporation', 'CMF Registration'],
    Cooperative: ['Cooperative Registry Entry'],
    'Non-Profit': ['Ministry of Justice Registration'],
  },
  Colombia: {
    'Sole Proprietorship': ['RUT Registration', 'DIAN Tax Identification'],
    Partnership: ['Chamber of Commerce Registration', 'RUT'],
    'SAS (LLC)': ['Articles of Incorporation', 'RUT'],
    Corporation: ['Stock Market Registration', 'RUT'],
    Cooperative: ['Confecoop Registration'],
    'Non-Profit': [
      'Chamber of Commerce Registration',
      'Tax-Exempt Certificate',
    ],
  },
  Peru: {
    'Sole Proprietorship': ['RUC Registration', 'SUNAT Tax Number'],
    Partnership: ['Public Deed of Partnership', 'RUC'],
    'EIRL (LLC)': ['SUNARP Registration', 'RUC'],
    'S.A. (Corporation)': [
      'Stock Exchange Listing (if applicable)',
      'SUNARP Registration',
    ],
    Cooperative: ['Superintendencia de Banca Registration'],
    'Non-Profit': ['Municipal Registration', 'Tax-Exempt Status'],
  },
  Ecuador: {
    'Sole Proprietorship': ['RUC Registration', 'SRI Tax Identification'],
    Partnership: ['Partnership Agreement', 'RUC'],
    LLC: ['Superintendencia de Compañías Registration', 'RUC'],
    Corporation: [
      'Superintendencia Registration',
      'Stock Market Registration (if applicable)',
    ],
    Cooperative: ['Superintendencia de Economía Popular Registration'],
    'Non-Profit': ['Ministry of Economic and Social Inclusion Approval'],
  },
  Bolivia: {
    'Sole Proprietorship': ['NIT Registration', 'Municipal Tax License'],
    Partnership: ['Partnership Deed', 'NIT'],
    LLC: ['Commercial Registry Registration', 'NIT'],
    Corporation: ['Stock Exchange Listing (if applicable)', 'NIT'],
    Cooperative: ['Cooperative Registry Approval'],
    'Non-Profit': ['Prefecture Registration', 'Tax-Exempt Certificate'],
  },
  Paraguay: {
    'Sole Proprietorship': ['RUC Registration', 'SET Tax Number'],
    Partnership: ['Public Deed of Partnership', 'RUC'],
    'SA (Corporation)': [
      'Stock Exchange Listing (if applicable)',
      'Ministry of Industry Registration',
    ],
    Cooperative: ['National Cooperative Institute Registration'],
    'Non-Profit': ['Government Registration', 'Tax Exemption Certificate'],
  },
  Uruguay: {
    'Sole Proprietorship': ['DGI Registration', 'BPS Registration'],
    Partnership: ['DGI Registration', 'Partnership Agreement'],
    Corporation: [
      'Articles of Incorporation',
      'Stock Market Registration (if applicable)',
    ],
    Cooperative: ['Ministry of Labor Registration'],
    'Non-Profit': ['National Registration of Associations'],
  },
  Venezuela: {
    'Sole Proprietorship': ['RIF Registration', 'SENIAT Tax Number'],
    Partnership: ['Public Deed of Partnership', 'RIF'],
    LLC: ['SNC Registration', 'RIF'],
    Corporation: [
      'Stock Market Registration (if applicable)',
      'SNC Registration',
    ],
    Cooperative: ['SUNACOOP Registration'],
    'Non-Profit': ['Ministry of Economy Registration', 'Tax Exempt Status'],
  },
  'Costa Rica': {
    'Sole Proprietorship': [
      'Registro Nacional Entry',
      'Tax Identification Number',
    ],
    Partnership: ['Public Deed of Partnership', 'Registro Nacional Entry'],
    Corporation: ['Articles of Incorporation', 'Registro Nacional Entry'],
    Cooperative: ['Cooperative National Institute Registration'],
    'Non-Profit': ['Ministry of Finance Registration'],
  },
  'Dominican Republic': {
    'Sole Proprietorship': ['RNC Registration', 'DGII Tax Registration'],
    Partnership: ['Partnership Agreement', 'RNC'],
    Corporation: [
      'General Business Registry Entry',
      'Stock Market Registration (if applicable)',
    ],
    Cooperative: ['Superintendencia de Bancos Registration'],
    'Non-Profit': ['Government Registration', 'Tax Exemption Certificate'],
  },
  Panama: {
    'Sole Proprietorship': ['RUC Registration', 'DGI Tax Number'],
    Partnership: ['Commercial Registry Entry', 'RUC'],
    Corporation: [
      'Stock Market Registration (if applicable)',
      'DGI Registration',
    ],
    Cooperative: ['Ministry of Commerce Registration'],
    'Non-Profit': ['Government Approval', 'Tax-Exempt Status'],
  },
};

export const OutletCategories = {
  'Physical Retail & Service Outlets': [
    'Standalone Retail Store',
    'Mall Outlet',
    'Department Store',
    'Supermarket / Hypermarket',
    'Convenience Store',
    'Discount Store / Dollar Store',
    'Warehouse Club / Wholesale Outlet',
    'Electronics & Appliance Store',
    'Luxury Boutique',
    'Sporting Goods Store',
    'Bookstore / Comic Shop',
    'Furniture & Home Decor Store',
    'Toy & Hobby Store',
    'Salon / Barbershop',
    'Spa & Wellness Center',
    'Nail Salon',
    'Tattoo & Piercing Studio',
    'Fitness Studio / Gym',
    'Car Dealership & Auto Service',
    'Dry Cleaning & Laundry Service',
    'Pet Grooming & Pet Supply Store',
    'Pharmacy & Health Store',
    'Coworking Space & Business Centers',
    'Café / Coffee Shop',
    'Restaurant',
    'Bakery & Patisserie',
    'Dessert & Ice Cream Shop',
    'Fast Food Franchise',
    'Steakhouse / BBQ / Grill House',
    'Sushi Bar / Asian Eatery',
    'Healthy Food Outlet',
    'Gaming Arcade / Esports Café',
    'Bowling Alley',
    'Movie Theater / Cinema',
    'Indoor Play Area & Trampoline Park',
    'Escape Room & VR Experience Centers',
  ],
  'Mobile & Flexible Outlets': [
    'Food Truck',
    'Beverage Cart',
    'Ice Cream Truck',
    'Street Food Kiosk',
    'Retail & Service Vans',
    'Mobile Clothing / Boutique Truck',
    'Mobile Salon & Spa',
    'Mobile Pet Grooming',
    'Mobile Auto Detailing',
    'Mobile Repair & Tech Support Van',
    'Pop-Up & Roaming Services',
    'Temporary Farmer’s Market Stall',
    'Mobile Bookstore & Library Van',
    'Traveling Fashion & Jewelry Market Stall',
  ],
  'Temporary & Event-Based Outlets': [
    'Christmas Market Stall',
    'Halloween Pop-Up Store',
    'Valentine’s Day Booth',
    'Food & Beverage Stall at Festivals',
    'Merch Booth at Concerts & Sporting Events',
    'Product Demo Booth at Trade Shows & Expos',
    'Temporary Showroom',
    'Branded Experience Kiosk',
    'Roadshow / Sampling Booth',
  ],
  'Online & Delivery-Centric Outlets': [
    'Online Store (Own Website)',
    'Marketplace Seller (Amazon, eBay, Etsy, etc.)',
    'Social Commerce (Instagram Shop, Facebook Marketplace)',
    'Cloud Kitchen / Virtual Restaurant',
    'Grocery Delivery Service',
    'Subscription Box Service',
    'Online Tutoring / Coaching Service',
    'Telehealth & Virtual Consultation',
    'Digital Marketing & Consulting Agency',
  ],
  'Specialty & Unconventional Outlets': [
    'Hotel Retail Store',
    'Resort Boutique',
    'Hospital Café / Pharmacy',
    'Wellness Spa inside a Medical Center',
    'Airport Duty-Free Store',
    'College Campus Store',
  ],
};
