export const ExpectedDownlineAdminHeaders = [
  'email',
  'name',
  'countryCode',
  'phone',
  'role',
];

export const ExpectedBusinessListingHeaders = [
  'logo',
  'cover',
  'name',
  'description',
  'addressLine1',
  'addressLine2',
  'city',
  'state',
  'country',
  'postalCode',
  'latitude',
  'longitude',
  'phone',
  'countryCode',
  'email',
  'website',
  'openingTime',
  'closingTime',
  'busyTime',
  'slowTime',
  'rating',
  'menu',
  'categories',
  'industry',
  'scalabilityFactor',
];
