// ─────────────────────────────────────────────────────────────────────────────
//  reviewSummary.model.ts
//
//  Per-business condensed summary of reviews, used as grounding for the
//  consumer review chatbot. Generated by a periodic job (or on first chat
//  if missing). One document per (business, source) pair.
//
//  Why a cached summary?
//    Sending 100+ raw reviews into every chat call is expensive and slow.
//    The summary distills positive/negative themes, representative quotes,
//    and aggregate stats into ~2KB that the LLM reads as context.
// ─────────────────────────────────────────────────────────────────────────────

import mongoose, { Schema, Document, Types } from "mongoose";

export interface IThemeMention {
  theme: string;
  mentions: number;
  quotes: string[];
}

export interface IReviewSummary extends Document {
  business: Types.ObjectId;
  source: string;

  totalReviews: number;
  averageRating: number;
  ratingDistribution: {
    one: number;
    two: number;
    three: number;
    four: number;
    five: number;
  };

  positiveThemes: IThemeMention[];
  negativeThemes: IThemeMention[];

  factualClaims: string[];

  recentTrend: "improving" | "stable" | "declining" | "insufficient_data";
  windowStart: Date;
  windowEnd: Date;

  generatedAt: Date;
  generatedFromReviewIds: Types.ObjectId[];
  modelUsed: string;
  tokensUsed?: number;

  createdAt: Date;
  updatedAt: Date;
}

const ThemeMentionSchema = new Schema<IThemeMention>(
  {
    theme: { type: String, required: true },
    mentions: { type: Number, required: true, default: 0 },
    quotes: { type: [String], default: [] },
  },
  { _id: false }
);

const ReviewSummarySchema = new Schema<IReviewSummary>(
  {
    business: {
      type: Schema.Types.ObjectId,
      required: true,
      index: true,
    },
    source: { type: String, required: true, default: "google_maps" },

    totalReviews: { type: Number, required: true, default: 0 },
    averageRating: { type: Number, required: true, default: 0 },
    ratingDistribution: {
      one: { type: Number, default: 0 },
      two: { type: Number, default: 0 },
      three: { type: Number, default: 0 },
      four: { type: Number, default: 0 },
      five: { type: Number, default: 0 },
    },

    positiveThemes: { type: [ThemeMentionSchema], default: [] },
    negativeThemes: { type: [ThemeMentionSchema], default: [] },

    factualClaims: { type: [String], default: [] },

    recentTrend: {
      type: String,
      enum: ["improving", "stable", "declining", "insufficient_data"],
      default: "insufficient_data",
    },
    windowStart: { type: Date, required: true },
    windowEnd: { type: Date, required: true },

    generatedAt: { type: Date, required: true, default: Date.now },
    generatedFromReviewIds: { type: [Schema.Types.ObjectId], default: [] },
    modelUsed: { type: String, required: true },
    tokensUsed: Number,
  },
  {
    timestamps: true,
    collection: "review_summaries",
  }
);

ReviewSummarySchema.index(
  { business: 1, source: 1 },
  { unique: true, name: "idx_business_source_unique" }
);
ReviewSummarySchema.index({ generatedAt: 1 }, { name: "idx_generated_at" });

export const ReviewSummaryModel = mongoose.model<IReviewSummary>(
  "ReviewSummary",
  ReviewSummarySchema
);
