import { UserSchema } from 'src/user/models/user.model';

export const DefaultBusinessOwnerRole = {
  name: 'Business Owner',
  creatorType: 'Business',
  belongsTo: 'Business',
  isSuperAdmin: false,
  isBusinessOwner: true,
  // privileges: {
  //   BUSINESS: ['create', 'read', 'update', 'delete'],
  //   PRODUCTS: ['create', 'read', 'update', 'delete'],
  //   ORDERS: ['create', 'read', 'update', 'delete'],
  //   PAYMENTS: ['create', 'read', 'update', 'delete'],
  //   COUPONS: ['create', 'read', 'update', 'delete'],
  // },
};
export const DefaultAdminRoles = {
  Sales_User: {
    name: 'Sales User',
    privileges: {
      DASHBOARD: ['READ'],
      BUSINESSES: ['READ'],
      CONSUMERS: ['READ'],
      MY_USERS: ['READ'],
      ANALYTICS: ['READ'],
    },
  },
  Sales_Manager: {
    name: 'Sales Manager',
    privileges: {
      DASHBOARD: ['READ'],
      BUSINESSES: ['READ'],
      CONSUMERS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      MY_USERS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      ANALYTICS: ['READ'],
    },
  },
  Support_Executive: {
    name: 'Support Executive',
    privileges: {
      MY_USERS: ['READ', 'UPDATE'],
      REPORTED_CONTENT: ['READ'],
      ANALYTICS: ['READ'],
    },
  },
  Support_Manager: {
    name: 'Support Manager',
    privileges: {
      MY_USERS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      REPORTED_CONTENT: ['READ', 'UPDATE'],
      ANALYTICS: ['READ'],
    },
  },
  Finance_User: {
    name: 'Finance User',
    privileges: {
      ANALYTICS: ['READ'],
      STORAGE: ['READ'],
    },
  },
  Finance_Manager: {
    name: 'Finance Manager',
    privileges: {
      ANALYTICS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      STORAGE: ['READ', 'UPDATE'],
    },
  },
  Marketing_User: {
    name: 'Marketing User',
    privileges: {
      CONTENT_CATEGORIES: ['CREATE', 'READ'],
      CONTENT_TEMPLATES: ['READ'],
    },
  },
  Marketing_Manager: {
    name: 'Marketing Manager',
    privileges: {
      CONTENT_CATEGORIES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      CONTENT_TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      REPORTED_CONTENT: ['READ'],
    },
  },
  Product_Admin: {
    name: 'Product Admin',
    privileges: {
      CONTENT_CATEGORIES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      CONTENT_TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      CONTENT_ETL: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    },
  },
  Operations_User: {
    name: 'Operations User',
    privileges: {
      BUSINESSES: ['READ'],
      STORAGE: ['READ', 'UPDATE'],
      DASHBOARD: ['READ'],
    },
  },
  Operations_Manager: {
    name: 'Operations Manager',
    privileges: {
      BUSINESSES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      DASHBOARD: ['READ'],
      ANALYTICS: ['READ'],
    },
  },
  IT_Support: {
    name: 'IT Support',
    privileges: {
      EXPLORE_SETTINGS: ['READ', 'UPDATE'],
      ROLES_AND_PRIVILEGES: ['READ'],
    },
  },
  IT_Manager: {
    name: 'IT Manager',
    privileges: {
      EXPLORE_SETTINGS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      ROLES_AND_PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      // PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE']
    },
  },
  Outlet_Manager: {
    name: 'Outlet Manager',
    privileges: {
      STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    },
  },
};
export const DefaultBusinessRoles = {
  Store_Manager: {
    name: 'Store Manager',
    creatorType: 'Business',
    belongsTo: 'Business',
    isSuperAdmin: false,
    isBusinessOwner: false,
    privileges: {
      DASHBOARD: ['READ'],
      CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      TEMPLATES: ['CREATE', 'READ'],
    },
  },
  General_Manager: {
    name: 'General Manager',
    creatorType: 'Business',
    belongsTo: 'Business',
    isSuperAdmin: false,
    isBusinessOwner: false,
    privileges: {
      DASHBOARD: ['READ'],
      CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      ROLES_AND_PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      SUBSCRIPTION: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE'],
    },
  },
  Regional_Manager: {
    name: 'Regional Manager',
    creatorType: 'Business',
    belongsTo: 'Business',
    isSuperAdmin: false,
    isBusinessOwner: false,
    privileges: {
      DASHBOARD: ['READ'],
      CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    },
  },
  Operational_Manager: {
    name: 'Operations Manager',
    creatorType: 'Business',
    belongsTo: 'Business',
    isSuperAdmin: false,
    isBusinessOwner: false,
    privileges: {
      DASHBOARD: ['READ'],
      CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
      TEMPLATES: ['READ'],
      BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    },
  },
};

export const DefaultBusinessDepartmentRoles = [
  {
    name: 'Operations',
    description: 'Manages day-to-day business operations.',
    roles: [
      {
        name: 'Store Manager',
        creatorType: 'Business',
        belongsTo: 'Business',
        isSuperAdmin: false,
        isBusinessOwner: false,
        privileges: {
          DASHBOARD: ['READ'],
          CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          TEMPLATES: ['CREATE', 'READ'],
        },
      },
      {
        name: 'General Manager',
        creatorType: 'Business',
        belongsTo: 'Business',
        isSuperAdmin: false,
        isBusinessOwner: false,
        privileges: {
          DASHBOARD: ['READ'],
          CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          ROLES_AND_PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          SUBSCRIPTION: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE'],
        },
      },
      {
        name: 'Regional Manager',
        creatorType: 'Business',
        belongsTo: 'Business',
        isSuperAdmin: false,
        isBusinessOwner: false,
        privileges: {
          DASHBOARD: ['READ'],
          CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
        },
      },
      {
        name: 'Operations Manager',
        creatorType: 'Business',
        belongsTo: 'Business',
        isSuperAdmin: false,
        isBusinessOwner: false,
        privileges: {
          DASHBOARD: ['READ'],
          CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
          TEMPLATES: ['READ'],
          BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
        },
      },
    ],
  },
  // {
  //   name: 'Marketing',
  //   description:
  //     'Responsible for promoting products and enhancing brand image.',
  //   roles: [
  //     {
  //       name: 'Marketing Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         COUPONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         BANNERS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         BRANDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //       },
  //     },
  //   ],
  // },
  // {
  //   name: 'Finance',
  //   description: 'Handles financial transactions, reporting, and budgeting.',
  //   roles: [
  //     {
  //       name: 'Finance Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         PAYMENTS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REPORTS: ['READ'],
  //       },
  //     },
  //   ],
  // },
  // {
  //   name: 'Customer Support',
  //   description: 'Provides assistance and support to customers.',
  //   roles: [
  //     {
  //       name: 'Support Executive',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         MESSAGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         NOTIFICATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //       },
  //     },
  //   ],
  // },
  // {
  //   name: 'Sales',
  //   description: 'Drives revenue through customer acquisition and retention.',
  //   roles: [
  //     {
  //       name: 'Regional Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //       },
  //     },
  //     {
  //       name: 'General Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         ROLES_AND_PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         SUBSCRIPTION: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE'],
  //       },
  //     },
  //     {
  //       name: 'Store Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['CREATE', 'READ'],
  //       },
  //     },
  //   ],
  // },
  // {
  //   name: 'Product Management',
  //   description: 'Responsible for product planning and development.',
  //   roles: [
  //     {
  //       name: 'Operations Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['READ'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //       },
  //     },
  //     {
  //       name: 'General Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         ROLES_AND_PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         SUBSCRIPTION: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE'],
  //       },
  //     },
  //   ],
  // },
  // {
  //   name: 'Human Resources',
  //   description:
  //     'Manages recruitment, employee relations, and personnel policies.',
  //   roles: [
  //     {
  //       name: 'General Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         ROLES_AND_PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         SUBSCRIPTION: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE'],
  //       },
  //     },
  //   ],
  // },
  // {
  //   name: 'Logistics',
  //   description: 'Oversees supply chain, inventory, and product distribution.',
  //   roles: [
  //     {
  //       name: 'Store Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['CREATE', 'READ'],
  //       },
  //     },
  //     {
  //       name: 'Operations Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['READ'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //       },
  //     },
  //   ],
  // },
  // {
  //   name: 'IT and Systems',
  //   description: 'Manages IT infrastructure, software, and technical support.',
  //   roles: [
  //     {
  //       name: 'Operations Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['READ'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //       },
  //     },
  //     // {
  //     //   name: 'Support Executive',
  //     //   creatorType: 'Business',
  //     //   belongsTo: 'Business',
  //     //   isSuperAdmin: false,
  //     //   isBusinessOwner: false,
  //     //   privileges: {
  //     //     MESSAGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //     //     NOTIFICATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //     //   },
  //     // },
  //   ],
  // },
  // {
  //   name: 'Quality Assurance',
  //   description:
  //     'Ensures product and service quality through testing and evaluation.',
  //   roles: [
  //     {
  //       name: 'Operations Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['READ'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //       },
  //     },
  //     {
  //       name: 'General Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         ROLES_AND_PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         SUBSCRIPTION: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE'],
  //       },
  //     },
  //   ],
  // },
  // {
  //   name: 'Legal and Compliance',
  //   description:
  //     'Ensures adherence to legal regulations and compliance standards.',
  //   roles: [
  //     {
  //       name: 'Finance Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         SUBSCRIPTION: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         // REPORTS: ['READ'],
  //       },
  //     },
  //     {
  //       name: 'General Manager',
  //       creatorType: 'Business',
  //       belongsTo: 'Business',
  //       isSuperAdmin: false,
  //       isBusinessOwner: false,
  //       privileges: {
  //         DASHBOARD: ['READ'],
  //         CONTENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         REWARDS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         STORAGE: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         LOCATIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         ROLES_AND_PRIVILEGES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEAM: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         TEMPLATES: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         SUBSCRIPTION: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  //         BUSINESS_PROFILE: ['CREATE', 'READ', 'UPDATE'],
  //       },
  //     },
  //   ],
  // },
];
