import { Admin } from 'src/admin/models/admin.model';
import { Business } from 'src/business/model/business.model';
import { CarouselType, DeviceTypes } from 'src/enums/auth.enums';
import { EventTypes } from 'src/enums/event.enums';
import { RoleBelonging, Roles } from 'src/roles/enums/roles.enum';
import { DurationType } from 'src/subscription/models/subscriptionProduct.model';

export enum BusinessIndustries {
  FOOD_DRINK = 'Food & Drink',
  RETAIL = 'Retail',
  HEALTH_BEAUTY = 'Health & Beauty',
  FITNESS_WELLNESS = 'Fitness & Wellness',
  ENTERTAINMENT = 'Entertainment',
  AUTOMOTIVE_SERVICES = 'Automotive Services',
  HOME_SERVICES = 'Home Services',
  PET_SERVICES = 'Pet Services',
  HOSPITALITY = 'Hospitality',
  PROFESSIONAL_SERVICES = 'Professional Services',
}

export enum EventCategory {
  ART = 'Art',
  GROOMING = 'Grooming',
  CHARITY = 'Charity',
  CLUBS = 'Clubs',
  DAYS_OUT = 'Days Out',
  ENTERTAINMENT = 'Entertainment',
  DINING = 'Dining',
  HAPPY_HOUR = 'Happy Hour',
  FITNESS = 'Fitness',
  ATTRACTIONS = 'Attractions',
  NIGHTLIFE = 'Nightlife',
  PETS = 'Pets',
  SPORTS = 'Sports',
  SHOPPING = 'Shopping',
}

export enum BusinessSubCategory {
  RESTAURANT = 'Restaurant',
  CAFE_COFFEE_SHOP = 'Cafe/Coffee Shop',
  BAKERY = 'Bakery',
  BAR = 'Bar',
  JUICE_BAR = 'Juice Bar',
  FOOD_TRUCK = 'Food Truck',
  CATERING_SERVICES = 'Catering Services',
  CLOUD_KITCHEN = 'Cloud Kitchen',
  FROZEN_DESSERTS = 'Frozen Desserts',

  ELECTRONICS_GADGETS = 'Electronics & Gadgets',
  CLOTHING_APPAREL = 'Clothing & Apparel',
  CONVENIENCE_STORE = 'Convenience Store',
  HOME_DECOR = 'Home Decor',
  STATIONERY = 'Stationery',
  GIFT_SHOP = 'Gift Shop',
  TOY_HOBBY_STORE = 'Toy & Hobby Store',
  JEWELRY_ACCESSORIES = 'Jewelry & Accessories',
  SMOKE_SHOP = 'Smoke Shop',
  THRIFT_STORE = 'Thrift Store',

  BEAUTY_COSMETICS = 'Beauty & Cosmetics',
  PET_SUPPLIES = 'Pet Supplies',
  SALON = 'Salon',
  SKINCARE_AESTHETICS = 'Skincare/ Aesthetics',
  SPA_MASSAGE = 'Spa & Massage',
  NAIL_BAR = 'Nail Bar',
  COSMETIC_SERVICES = 'Cosmetic Services',
  DERMATOLOGY_CLINIC = 'Dermatology Clinic',
  TANNING_STUDIO = 'Tanning Studio',

  FITNESS_CENTER = 'Fitness Center',
  YOGA_STUDIO = 'Yoga Studio',
  MARTIAL_ARTS = 'Martial Arts',
  PERSONAL_TRAINING = 'Personal Training',
  DANCE_STUDIO = 'Dance Studio',
  PHYSIOTHERAPY = 'Physiotherapy',
  WELLNESS_COACHING = 'Wellness Coaching',
  MEDITATION_CENTER = 'Meditation Center',

  EVENT_PLANNING = 'Event Planning',
  PARTY_RENTALS = 'Party Rentals',
  AMUSEMENT_CENTER = 'Amusement Center',
  ESCAPE_ROOM = 'Escape Room',
  LOCAL_EXPERIENCES = 'Local Experiences',
  PERFORMER_SERVICES = 'Performer Services',
  KIDS_ENTERTAINMENT = 'Kids Entertainment',
  PHOTOGRAPHY = 'Photography',

  GARAGE = 'Garage',
  DETAILING = 'Detailing',
  AUTO_ACCESSORIES = 'Auto Accessories',
  RENTAL = 'Rental',
  CUSTOMIZATION = 'Customization',

  HOME_CLEANING = 'Home Cleaning',
  ELECTRICAL_SERVICES = 'Electrical Services',
  PLUMBING_SERVICES = 'Plumbing Services',
  PEST_CONTROL = 'Pest Control',
  APPLIANCE_REPAIR = 'Appliance Repair',
  HANDYMAN_SERVICES = 'Handyman Services',
  GARDENING = 'Gardening',
  INTERIOR_DESIGN = 'Interior Design',
  MOVING_STORAGE = 'Moving & Storage',

  PET_GROOMING = 'Pet Grooming',
  PET_TRAINING = 'Pet Training',
  VETERINARY_CLINIC = 'Veterinary Clinic',
  PET_BOARDING = 'Pet Boarding',
  PET_ADOPTION_CENTER = 'Pet Adoption Center',
  PET_SUPPLIES_STORE = 'Pet Supplies Store',
  PET_WALKING_SERVICES = 'Pet Walking Services',

  HOTEL = 'Hotel',
  BED_BREAKFAST = 'Bed & Breakfast',
  HOMESTAY = 'Homestay',
  HOSTEL = 'Hostel',
  VACATION_RENTALS = 'Vacation Rentals',
  CAMPGROUNDS = 'Campgrounds',

  ACCOUNTING_CONSULTANT = 'Accounting Consultant',
  LEGAL_SERVICES = 'Legal Services',
  BUSINESS_CONSULTANT = 'Business Consultant',
  EDUCATION = 'Education',
  TRANSLATION = 'Translation',
}

export const PinntagBusinessSeeder = {
  name: 'PinnTag Limited',
  countryCode: '+44',
  phone: '7917303330',
  email: 'support@pinntag.com',
  website: 'www.pinntag.com',
  isActive: true,
};
export const Seeder = {
  ContentCategories: [
    {
      title: 'Art',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/Arts+and+craft.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/Arts+and+craft.svg',
      activeColor: '#F1F3C2',
      description: 'Art & Crafts',
    },
    {
      title: 'Grooming',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/Beauty+n+spa.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/Beauty+n+spa.svg',
      activeColor: '#F7B5CA',
      description: 'Beauty & Spa',
    },
    {
      title: 'Charity',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/charity.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/charity.svg',
      activeColor: '#A1EEBD',
      description: 'Charity',
    },
    {
      title: 'Clubs',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/Club+and+classes.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/Club+and+classes.svg',
      activeColor: '#A6D6D6',
      description: 'Clubs & Classes',
    },
    {
      title: 'Days Out',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/Happy+hour.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/Happy+hour.svg',
      activeColor: '#FFF1D5',
      description: 'Days Out',
    },
    {
      title: 'Entertainment',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/entertainment.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/entertainment.svg',
      activeColor: '#D9EAFD',
      description: 'Entertainment',
    },
    {
      title: 'Dining',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/Food+and+drinks.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/Food+and+drinks.svg',
      activeColor: '#FFCDB2',
      description: 'Food & Drinks',
    },
    {
      title: 'Happy Hour',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/Happy+hour.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/Happy+hour.svg',
      activeColor: '#FFE1E0',
      description: 'Happy Hour',
    },
    {
      title: 'Fitness',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/Health+and+fitness.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/Health+and+fitness.svg',
      activeColor: '#CDFAD5',
      description: 'Health & Fitness',
    },
    {
      title: 'Attractions',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/retails.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/retails.svg',
      activeColor: '#FFE3E3',
      description: 'Local Attractions',
    },
    {
      title: 'Nightlife',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/entertainment.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/entertainment.svg',
      activeColor: '#8EACCD',
      description: 'Music & Nightlife',
    },
    {
      title: 'Pets',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/pets.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/pets.svg',
      activeColor: '#D4F6FF',
      description: 'Pets',
    },
    {
      title: 'Shopping',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/retails.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/retails.svg',
      activeColor: '#BFD8AF',
      description: 'Retail',
    },
    {
      title: 'Sports',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Light+Icons/sports.png',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Content+Category+Icons/Dark+Icons/sports.svg',
      activeColor: '#FFCCEA',
      description: 'Sports',
    },
  ],

  roles: [
    // {
    //   name: Roles.ADMIN,
    //   creatorType: 'System',
    //   belongsTo: RoleBelonging.SYSTEM,
    // },
    {
      name: Roles.USER,
      creatorType: 'System',
      belongsTo: RoleBelonging.SYSTEM,
    },
    // {
    //   name: Roles.SUB_ADMIN,
    //   creatorType: 'System',
    // },
    // {
    //   name: Roles.STAFF,
    //   creatorType: 'System',
    // },
    {
      name: Roles.GUEST,
      creatorType: 'System',
      belongsTo: RoleBelonging.SYSTEM,
    },
    // {
    //   name: Roles.BUSINESS_PROFILE,
    //   creatorType: 'System',
    // },
  ],
  keywords: [
    {
      name: 'Dinner',
      color: '#FF0000',
    },
    {
      name: 'Live Music',
      color: '#FF0000',
    },
    {
      name: 'Cocktail Night',
      color: '#FF0000',
    },
    {
      name: 'Networking',
      color: '#FF0000',
    },
    {
      name: 'Food Tasting',
      color: '#FF0000',
    },
    {
      name: 'DJ Night',
      color: '#FF0000',
    },
    {
      name: 'Happy Hour',
      color: '#FF0000',
    },
    {
      name: 'Dance Floor',
      color: '#FF0000',
    },
    {
      name: 'Social Gathering',
      color: '#FF0000',
    },
    {
      name: 'Theme Night',
      color: '#FF0000',
    },
    {
      name: 'Pizza',
      color: '#FF0000',
    },
    {
      name: 'Lunch',
      color: '#FF0000',
    },
  ],
  ageGroups: [
    {
      sortOrder: 0,
      name: 'all',
      image: '',
      description: '',
    },
    {
      sortOrder: 1,
      name: '16-19',
      image: '',
      description: '',
    },
    {
      sortOrder: 2,
      name: '20-25',
      image: '',
      description: '',
    },
    {
      sortOrder: 3,
      name: '26-34',
      image: '',
      description: '',
    },
    {
      sortOrder: 4,
      name: '35-45',
      image: '',
      description: '',
    },
    {
      sortOrder: 5,
      name: '46-55',
      image: '',
      description: '',
    },
    {
      sortOrder: 6,
      name: '56-65',
      image: '',
      description: '',
    },
    {
      sortOrder: 7,
      name: '66-74',
      image: '',
      description: '',
    },
    {
      sortOrder: 8,
      name: '75+',
      image: '',
      description: '',
    },
  ],
  subscriptionProducts: [
    {
      name: 'Annual',
      description: 'Pay annually and save 25%',
      price: 479.99,
      durationType: DurationType.ANNUAL,
      duration: 1,
      isRecommended: true,
      stripeProductId: 'price_1PD5hKDkH0yJD0lhyKPKC1in',
    },
    {
      name: 'Monthly',
      description: 'Pay monthly',
      price: 49.99,
      durationType: DurationType.MONTHLY,
      duration: 1,
      isRecommended: false,
      stripeProductId: 'price_1PD5epDkH0yJD0lhkeroy5jp',
    },
    {
      name: 'Free',
      description: 'Free subscription for 30 days',
      price: 0.0,
      durationType: DurationType.MONTHLY,
      duration: 1,
      isRecommended: false,
    },
  ],

  appVersions: [
    {
      deviceType: DeviceTypes.ANDROID,
      version: '1.1.3',
      description: 'Initial release',
    },
    {
      deviceType: DeviceTypes.IOS,
      version: '1.1.3',
      description: 'Initial release',
    },
    {
      deviceType: DeviceTypes.WEB,
      version: '1.0.0',
      description: 'Initial release',
    },
  ],
  fileCategories: [
    {
      name: 'profile picture',
    },
    {
      name: 'thumbnail',
    },
    {
      name: 'gallery image',
    },
    {
      name: 'logo',
    },
    {
      name: 'promotional image',
    },
    {
      name: 'promotional video',
    },
    {
      name: 'brochure',
    },
    {
      name: 'live stream recording',
    },
    {
      name: 'business license',
    },
    {
      name: 'tax document',
    },
    {
      name: 'ID Proof',
    },
    {
      name: 'invoice',
    },
    {
      name: 'Audio Note',
    },
    {
      name: 'Content QR',
    },
    {
      name: 'other',
    },
  ],
  BusinessIndustries: [
    {
      title: 'Food & Drink',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Food+%26+Drink.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Food+%26+Drink.svg',
      activeColor: '#FFCDB2',
    },
    {
      title: 'Retail',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Retails.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Retails.svg',
      activeColor: '#8EACCD',
    },
    {
      title: 'Health & Beauty',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Health+%26+Beauty.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Health+%26+Beauty.svg',
      activeColor: '#AC87C5',
    },
    {
      title: 'Fitness & Wellness',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Fitness+%26+Wellness.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Fitness+%26+Wellness.svg',
      activeColor: '#A1EEBD',
    },
    {
      title: 'Entertainment',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Entertainment+%26+Experiences.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Entertainment+%26+Experiences.svg',
      activeColor: '#F6F193',
    },
    {
      title: 'Automotive Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Automotive+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Automotive+Services.svg',
      activeColor: '#CCD3CA',
    },
    {
      title: 'Home Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Home+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Home+Services.svg',
      activeColor: '#EECEB9',
    },
    {
      title: 'Pet Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Pet+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Pet+Services.svg',
      activeColor: '#D4F6FF',
    },
    {
      title: 'Hospitality',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Hospitality.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Hospitality.svg',
      activeColor: '#AC87C5',
    },
    {
      title: 'Professional Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Light/Professional+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Industry/Dark/Professional+Services.svg',
      activeColor: '#BED7DC',
    },
  ],
  BusinessCategories: [
    {
      title: 'Restaurant',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Restaurant-Dine.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Restaurant-Dine.svg',
      activeColor: '#FFCDB2',
      industry: 'Food & Drink',
    },
    {
      title: 'Cafe/Coffee Shop',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Cafe-Coffee+Shop.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Cafe-Coffee+Shop.svg',
      activeColor: '#DFCCFB',
      industry: 'Food & Drink',
    },
    {
      title: 'Bakery',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Bakery-Desert+Shop.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Bakery-Desert+Shop.svg',
      activeColor: '#D4F6FF',
      industry: 'Food & Drink',
    },
    {
      title: 'Bar',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Bar-Lounge-Pub.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Bar-Lounge-Pub.svg',
      activeColor: '#CDFAD5',
      industry: 'Food & Drink',
    },
    {
      title: 'Juice Bar',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Juice-Smoothie+Bar.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Juice-Smoothie+Bar.svg',
      activeColor: '#F7B5CA',
      industry: 'Food & Drink',
    },
    {
      title: 'Food Truck',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Food+Truck-Mobile+Vendor.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Food+Truck-Mobile+Vendor.svg',
      activeColor: '#F6F193',
      industry: 'Food & Drink',
    },
    {
      title: 'Catering Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Catering+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Catering+Services.svg',
      activeColor: '#FDB7EA',
      industry: 'Food & Drink',
    },
    {
      title: 'Cloud Kitchen',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Cloud+Kitchen+-+Delivery+Only.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Cloud+Kitchen+-+Delivery+Only.svg',
      activeColor: '#F0F1C5',
      industry: 'Food & Drink',
    },
    {
      title: 'Desserts',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Light/Ice+Cream+-+Frozen+Desserts.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Food+%26+Drink/Dark/Ice+Cream+-+Frozen+Desserts.svg',
      activeColor: '#BED7DC',
      industry: 'Food & Drink',
    },

    {
      title: 'Clothing & Apparel',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Clothing+%26+Apparel.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Clothing+%26+Apparel.svg',
      activeColor: '#3498DB',
      industry: 'Retail',
    },
    {
      title: 'Electronics & Gadgets',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Electronics+%26+Gadgets.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Electronics+%26+Gadgets.svg',
      activeColor: '#2C3E50',
      industry: 'Retail',
    },
    {
      title: 'Convenience Store',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Grocery+%26+Convenience+Store.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Grocery+%26+Convenience+Store.svg',
      activeColor: '#58D68D',
      industry: 'Retail',
    },
    {
      title: 'Home Decor',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Home+Decor+-+Furniture.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Home+Decor+-+Furniture.svg',
      activeColor: '#D4AC0D',
      industry: 'Retail',
    },
    {
      title: 'Jewelry & Accessories',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Jewelry+%26+Accessories.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Jewelry+%26+Accessories.svg',
      activeColor: '#D98880',
      industry: 'Retail',
    },
    {
      title: 'Beauty & Cosmetics',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Beauty+%26+Cosmetics.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Beauty+%26+Cosmetics.svg',
      activeColor: '#AF7AC5',
      industry: 'Retail',
    },
    {
      title: 'Stationery',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Bookstore+-+Stationery.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Bookstore+-+Stationery.svg',
      activeColor: '#AAB7B8',
      industry: 'Retail',
    },
    {
      title: 'Toy & Hobby Store',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Toy+%26+Hobby+Store.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Toy+%26+Hobby+Store.svg',
      activeColor: '#F4D03F',
      industry: 'Retail',
    },
    {
      title: 'Pet Supplies',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Pet+Supplies.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Pet+Supplies.svg',
      activeColor: '#DC7633',
      industry: 'Retail',
    },
    {
      title: 'Smoke Shop',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Vape+-+Smoke+Shop.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Vape+-+Smoke+Shop.svg',
      activeColor: '#34495E',
      industry: 'Retail',
    },
    {
      title: 'Gift Shop',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Gift+%26+Souvenir+Shop.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Gift+%26+Souvenir+Shop.svg',
      activeColor: '#EC7063',
      industry: 'Retail',
    },
    {
      title: 'Thrift Store',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Light/Thrift+-+Second+Hand+Store.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Retails/Dark/Thrift+-+Second+Hand+Store.svg',
      activeColor: '#7D6608',
      industry: 'Retail',
    },
    {
      title: 'Salon',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Light/Salon+-+Hairdresser.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Dark/Salon+-+Hairdresser.svg',
      activeColor: '#D35400',
      industry: 'Health & Beauty',
    },
    {
      title: 'Spa & Massage',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Light/Spa+%26+Massage.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Dark/Spa+%26+Massage.svg',
      activeColor: '#A3E4D7',
      industry: 'Health & Beauty',
    },
    {
      title: 'Skincare/ Aesthetics',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Light/Skincare+-+Aesthetics.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Dark/Skincare+-+Aesthetics.svg',
      activeColor: '#F5B7B1',
      industry: 'Health & Beauty',
    },
    {
      title: 'Nail Bar',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Light/Nail+Bar.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Dark/Nail+Bar.svg',
      activeColor: '#F1948A',
      industry: 'Health & Beauty',
    },
    {
      title: 'Cosmetic Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Light/Cosmetic+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Dark/Cosmetic+Services.svg',
      activeColor: '#C39BD3',
      industry: 'Health & Beauty',
    },
    {
      title: 'Dermatology Clinic',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Light/Dermatology+-+Skin+Clinic.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Dark/Dermatology+-+Skin+Clinic.svg',
      activeColor: '#7FB3D5',
      industry: 'Health & Beauty',
    },
    {
      title: 'Tanning Studio',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Light/Tanning+Studio.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Health+%26+Beauty/Dark/Tanning+Studio.svg',
      activeColor: '#EDBB99',
      industry: 'Health & Beauty',
    },
    {
      title: 'Fitness Center',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Light/Gym+-+Fitness+Center.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Dark/Gym+-+Fitness+Center.svg',
      activeColor: '#1ABC9C',
      industry: 'Fitness & Wellness',
    },
    {
      title: 'Yoga Studio',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Light/Yoga+-+Pilates+Studio.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Dark/Yoga+-+Pilates+Studio.svg',
      activeColor: '#76D7C4',
      industry: 'Fitness & Wellness',
    },
    {
      title: 'Martial Arts',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Light/Martial+Arts+-+Boxing+Studio.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Dark/Martial+Arts+-+Boxing+Studio.svg',
      activeColor: '#2E4053',
      industry: 'Fitness & Wellness',
    },
    {
      title: 'Personal Training',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Light/Personal+Training.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Dark/Personal+Training.svg',
      activeColor: '#117864',
      industry: 'Fitness & Wellness',
    },
    {
      title: 'Dance Studio',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Light/Dance+Studio.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Dark/Dance+Studio.svg',
      activeColor: '#F39CBA',
      industry: 'Fitness & Wellness',
    },
    {
      title: 'Physiotherapy',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Light/Physiotherapy+-+Rehabilitation.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Dark/Physiotherapy+-+Rehabilitation.svg',
      activeColor: '#85C1E9',
      industry: 'Fitness & Wellness',
    },
    {
      title: 'Wellness Coaching',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Light/Wellness+Coaching.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Dark/Wellness+Coaching.svg',
      activeColor: '#45B39D',
      industry: 'Fitness & Wellness',
    },
    {
      title: 'Meditation Center',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Light/Meditation+Center.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Fitness+%26+Wellness/Dark/Meditation+Center.svg',
      activeColor: '#BB8FCE',
      industry: 'Fitness & Wellness',
    },
    {
      title: 'Event Planning',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/Event+Planning.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/Event+Planning.svg',
      activeColor: '#F5B041',
      industry: 'Entertainment',
    },
    {
      title: 'Party Rentals',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/Party+Rentals.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/Party+Rentals.svg',
      activeColor: '#DC7633',
      industry: 'Entertainment',
    },
    {
      title: 'Amusement Center',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/Amusement+Center+-+Arcade.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/Amusement+Center+-+Arcade.svg',
      activeColor: '#E74C3C',
      industry: 'Entertainment',
    },
    {
      title: 'Escape Room',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/Escape+Room+-+VR+Experience.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/Escape+Room+-+VR+Experience.svg',
      activeColor: '#5D6D7E',
      industry: 'Entertainment',
    },
    {
      title: 'Local Experiences',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/Tours+%26+Local+Experiences.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/Tours+%26+Local+Experiences.svg',
      activeColor: '#58D68D',
      industry: 'Entertainment',
    },
    {
      title: 'Performer Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/DJ+-+Performer+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/DJ+-+Performer+Services.svg',
      activeColor: '#AF601A',
      industry: 'Entertainment',
    },
    {
      title: 'Kids Entertainment',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/Kids+Entertainment.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/Kids+Entertainment.svg',
      activeColor: '#F7DC6F',
      industry: 'Entertainment',
    },
    {
      title: 'Photography',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/Photography+-+Videography.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/Photography+-+Videography.svg',
      activeColor: '#7FB3D5',
      industry: 'Entertainment',
    },
    {
      title: 'Garage',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Automotive+Services/Light/Garage.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Automotive+Services/Dark/Garage.svg',
      activeColor: '#5D6D7E',
      industry: 'Automotive Services',
    },
    {
      title: 'Detailing',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Automotive+Services/Light/Detailing.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Automotive+Services/Dark/Detailing.svg',
      activeColor: '#85929E',
      industry: 'Automotive Services',
    },
    {
      title: 'Auto Accessories',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Light/Photography+-+Videography.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Entertainment+%26+Experiences/Dark/Photography+-+Videography.svg',
      activeColor: '#2E4053',
      industry: 'Automotive Services',
    },
    {
      title: 'Rental',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Automotive+Services/Light/Rental+-+Leasing.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Automotive+Services/Dark/Rental+-+Leasing.svg',
      activeColor: '#1F618D',
      industry: 'Automotive Services',
    },
    {
      title: 'Customization',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Automotive+Services/Light/Customization+-+Wrapping.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Automotive+Services/Dark/Customization+-+Wrapping.svg',
      activeColor: '#884EA0',
      industry: 'Automotive Services',
    },
    {
      title: 'Home Cleaning',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Home+Cleaning.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Home+Cleaning.svg',
      activeColor: '#F9E79F',
      industry: 'Home Services',
    },
    {
      title: 'Electrical Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Electrical+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Electrical+Services.svg',
      activeColor: '#F4D03F',
      industry: 'Home Services',
    },
    {
      title: 'Plumbing Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Plumbing+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Plumbing+Services.svg',
      activeColor: '#5499C7',
      industry: 'Home Services',
    },
    {
      title: 'Pest Control',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Pest+Control.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Pest+Control.svg',
      activeColor: '#CD6155',
      industry: 'Home Services',
    },
    {
      title: 'Appliance Repair',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Appliance+Repair.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Appliance+Repair.svg',
      activeColor: '#45B39D',
      industry: 'Home Services',
    },
    {
      title: 'Handyman Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Handyman+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Handyman+Services.svg',
      activeColor: '#D98880',
      industry: 'Home Services',
    },
    {
      title: 'Gardening',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Landscaping+-+Gardening.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Landscaping+-+Gardening.svg',
      activeColor: '#229954',
      industry: 'Home Services',
    },
    {
      title: 'Interior Design',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Interior+Design+-+Renovation.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Interior+Design+-+Renovation.svg',
      activeColor: '#A04000',
      industry: 'Home Services',
    },
    {
      title: 'Moving & Storage',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Light/Moving+%26+Storage.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Home+Services/Dark/Moving+%26+Storage.svg',
      activeColor: '#7D3C98',
      industry: 'Home Services',
    },
    {
      title: 'Pet Grooming',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Light/Pet+Grooming.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Dark/Pet+Grooming.svg',
      activeColor: '#FAD7A0',
      industry: 'Pet Services',
    },
    {
      title: 'Pet Training',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Light/Pet+Training.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Dark/Pet+Training.svg',
      activeColor: '#EDBB99',
      industry: 'Pet Services',
    },
    {
      title: 'Veterinary Clinic',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Light/Veterinary+Clinic.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Dark/Veterinary+Clinic.svg',
      activeColor: '#A9CCE3',
      industry: 'Pet Services',
    },
    {
      title: 'Pet Boarding',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Light/Pet+Boarding+-+Daycare.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Dark/Pet+Boarding+-+Daycare.svg',
      activeColor: '#F7C5CC',
      industry: 'Pet Services',
    },
    {
      title: 'Pet Walking Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Light/Pet+Walking+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Dark/Pet+Walking+Services.svg',
      activeColor: '#ABEBC6',
      industry: 'Pet Services',
    },
    {
      title: 'Pet Adoption Center',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Light/Pet+Adoption+Center.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Dark/Pet+Adoption+Center.svg',
      activeColor: '#F9E79F',
      industry: 'Pet Services',
    },
    {
      title: 'Pet Supplies Store',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Light/Pet+Supplies+Store.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Pet+Services/Dark/Pet+Supplies+Store.svg',
      activeColor: '#DC7633',
      industry: 'Pet Services',
    },
    {
      title: 'Hotel',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Light/Hotel+-+Resort.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Dark/Hotel+-+Resort.svg',
      activeColor: '#1A5276',
      industry: 'Hospitality',
    },
    {
      title: 'Bed & Breakfast',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Light/Bed+%26+Breakfast.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Dark/Bed+%26+Breakfast.svg',
      activeColor: '#F8C471',
      industry: 'Hospitality',
    },
    {
      title: 'Homestay',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Light/Guest+House+-+Homestay.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Dark/Guest+House+-+Homestay.svg',
      activeColor: '#D7BDE2',
      industry: 'Hospitality',
    },
    {
      title: 'Hostel',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Light/Hostel+-+Backpacker+Lodging.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Dark/Hostel+-+Backpacker+Lodging.svg',
      activeColor: '#58D68D',
      industry: 'Hospitality',
    },
    {
      title: 'Vacation Rentals',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Light/Vacation+Rentals.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Dark/Vacation+Rentals.svg',
      activeColor: '#F5B041',
      industry: 'Hospitality',
    },
    {
      title: 'Campgrounds',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Light/Campgrounds+-+Glamping.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Hospitality/Dark/Campgrounds+-+Glamping.svg',
      activeColor: '#229954',
      industry: 'Hospitality',
    },
    {
      title: 'Accounting Consultant',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Light/Accounting+-+Tax+Consultant.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Dark/Accounting+-+Tax+Consultant.svg',
      activeColor: '#566573',
      industry: 'Professional Services',
    },
    {
      title: 'Legal Services',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Light/Legal+Services+-+Law+Firm.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Dark/Legal+Services+-+Law+Firm.svg',
      activeColor: '#1C2833',
      industry: 'Professional Services',
    },
    {
      title: 'Business Consultant',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Light/Business+Consultant.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Dark/Business+Consultant.svg',
      activeColor: '#2874A6',
      industry: 'Professional Services',
    },
    {
      title: 'Education',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Light/Education+-+Tutoring.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Dark/Education+-+Tutoring.svg',
      activeColor: '#82E0AA',
      industry: 'Professional Services',
    },
    {
      title: 'Translation',
      lightIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Light/Translation+-+Language+Services.svg',
      darkIcon:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Category/Professional+Services/Dark/Translation+-+Language+Services.svg',
      activeColor: '#B2BABB',
      industry: 'Professional Services',
    },
  ],
  EventTemplates: [
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '100',
      businessProfile: null,
      categories: ['Dining'],
      title: 'Free Coke with Any Burger!',
      keywords: ['burger', 'fast food', 'coke', 'free drink'],
      description:
        'Craving a delicious burger? Now’s the perfect time to indulge! For a limited period, enjoy a refreshing Coca-Cola completely FREE with every burger you purchase at our participating locations. Whether you’re into classic cheeseburgers, spicy chicken, or plant-based patties, each burger meal comes with an ice-cold Coke to complement the flavor and elevate your dining experience. Grab your friends, skip the kitchen, and treat yourself to a combo that satisfies both hunger and thirst without any extra cost. Just mention promo code FREECOKE during your visit. Valid while supplies last – don’t miss this chance to enjoy your favorite burger combo with a chilled Coke on us!',
      minTargetAge: 15,
      maxTargetAge: 50,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'FREECOKE',
      isFree: true,
      participationCost: '',
      termsApplied: true,
      termsAndConditions:
        'Offer valid for dine-in only. One Coke per burger. While supplies last.',
      businessIndustry: 'Food & Drink',
      businessCategories: ['Restaurant'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Coke/Free+Coke+With+Burger.png',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '50',
      businessProfile: null,
      categories: ['Dining'],
      title: 'Buy 2 Pizzas, Get 2 Cokes Free!',
      keywords: ['pizza', 'beverage', 'coke', 'combo deal'],
      description:
        "Make your next meal a celebration! When you order any two large pizzas, you’ll receive two chilled Coca-Colas absolutely FREE. This combo is perfect for pizza nights with family, gaming marathons with friends, or simply spoiling yourself after a long day. Our pizzas are made fresh using premium ingredients and loaded with bold flavors. Pair them with the crisp fizz of Coke and you've got a match made in food heaven. Use promo code PIZZA+COKE at checkout for delivery or takeaway. A delicious deal that brings joy to your table without extra cost. Hurry — valid for a limited time, one offer per order!",
      minTargetAge: 18,
      maxTargetAge: 45,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'PIZZA+COKE',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions:
        'Available for delivery and takeaway only. While supplies last. One offer per order.',
      businessIndustry: 'Food & Drink',
      businessCategories: ['Restaurant'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Coke/Buy+Pizza+Get+Coke.png',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FIXED',
      discountValue: '5',
      businessProfile: null,
      categories: ['Dining'],
      title: 'Coke Combo Lunch for Just $5!',
      keywords: ['lunch', 'combo', 'coke', 'meal deal'],
      description:
        "Take your lunch break to the next level with our value-packed $5 Coke Combo Lunch! For just five dollars, enjoy a satisfying meal that includes a hearty sandwich of your choice, a side of crispy golden fries, and an ice-cold Coca-Cola to complete the experience. Whether you're a busy professional, student, or just hungry for great food on a budget, this midday meal is designed to deliver flavor, freshness, and savings. Served fast, enjoyed best between 12pm and 3pm, this combo is your perfect lunch solution. Mention promo code LUNCH5 when ordering in-store or for pickup and enjoy a great lunch without breaking the bank.",
      minTargetAge: 18,
      maxTargetAge: 55,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'LUNCH5',
      isFree: false,
      participationCost: '$5',
      termsApplied: true,
      termsAndConditions:
        'Offer valid from 12pm–3pm daily. Dine-in and pickup only. No substitutions.',
      businessIndustry: 'Food & Drink',
      businessCategories: ['Restaurant'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Coke/Coke+Combo+Lunch.png',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '15',
      businessProfile: null,
      categories: ['Dining'],
      title: '15% Off All Vegan Desserts!',
      keywords: ['bakery', 'dessert', 'vegan', 'discount'],
      description:
        "Indulge your sweet tooth without any guilt by enjoying 15% off our entire range of vegan desserts. Whether you're a committed vegan or just looking to try healthier and plant-based options, our bakery offers a wide variety of treats including cakes, cookies, and pastries, all made with natural ingredients and no animal products. Perfect for anyone seeking delicious desserts that are kind to the environment and your body. This limited-time offer encourages you to explore the flavors of vegan baking with discounts on every item in the vegan section. Use promo code VEGANSWEET15 when you visit us in-store. It’s a wonderful way to treat yourself, friends, or family with sweets that everyone can enjoy. Don't miss out on this tasty deal, valid for one use per customer. Come savor the goodness while supporting sustainable eating choices.",
      minTargetAge: 16,
      maxTargetAge: 50,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'VEGANSWEET15',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions:
        'Offer valid in-store only. Limited to one use per customer.',
      businessIndustry: 'Food & Drink',
      businessCategories: ['Bakery', 'Desserts'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Vegan+Desserts.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '10',
      businessProfile: null,
      categories: ['Dining'],
      title: '10% Off All Breakfast Combos!',
      keywords: ['breakfast', 'cafe', 'morning deal', 'discount'],
      description:
        'Start your day the right way with 10% off all breakfast combo meals at our café. From hearty classics like eggs and bacon to lighter options like fresh fruit bowls and avocado toast, our breakfast combos are designed to fuel your morning efficiently and deliciously. Perfect for early risers, busy professionals, and families alike, this offer ensures you enjoy a nutritious start while saving money. Available for dine-in customers before 11 AM, this discount is ideal for those who want quality food in a cozy, welcoming environment. Use promo code BREAKFAST10 to claim your discount and make your morning brighter and tastier. Come in early and treat yourself to a great deal on the most important meal of the day!',
      minTargetAge: 16,
      maxTargetAge: 45,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'BREAKFAST10',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid before 11 AM. Dine-in only.',
      businessIndustry: 'Food & Drink',
      businessCategories: ['Cafe/Coffee Shop'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Breakfast+Combos+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '20',
      businessProfile: null,
      categories: ['Happy Hour'],
      title: '20% Off All Tap Beers!',
      keywords: ['bar', 'beer', 'happy hour', 'drinks'],
      description:
        'Celebrate happy hour with a refreshing 20% discount on all tap beers served at our bar from 6 PM to 9 PM daily. Whether you prefer crisp lagers, hoppy IPAs, rich stouts, or seasonal brews, our extensive selection of draft beers will satisfy every beer lover’s palate. Gather your friends and unwind after a long day in a lively and welcoming atmosphere while enjoying great savings on your favorite brews. This offer is valid for dine-in customers only and cannot be combined with other promotions. Use promo code TAPBEER20 to redeem your discount. Perfect for casual evenings, social gatherings, or after-work relaxation, this deal makes it easier to enjoy quality craft beers without stretching your budget. Cheers to good times and great beer!',
      minTargetAge: 21,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'TAPBEER20',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions:
        'Dine-in only. Valid during happy hour from 6 PM to 9 PM. Must be 21 or older.',
      businessIndustry: 'Food & Drink',
      businessCategories: ['Bar'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Tap+beer.jpeg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '20',
      businessProfile: null,
      categories: ['Happy Hour'],
      title: '20% Off Signature Cocktails!',
      keywords: ['bar', 'cocktails', 'happy hour', 'discount'],
      description:
        'Enjoy 20% off our signature cocktails during happy hour from 5 PM to 8 PM!',
      minTargetAge: 21,
      maxTargetAge: 50,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'CHEERS20',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid during happy hour only. Must be 21 or older.',
      businessIndustry: 'Food & Drink',
      businessCategories: ['Bar'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Signature+Cocktails!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '15',
      businessProfile: null,
      categories: ['Shopping'],
      title: '15% Off All Car Accessories!',
      keywords: ['auto accessories', 'car accessories', 'discount'],
      description:
        'Upgrade your ride with our premium car accessories, now at 15% off!',
      minTargetAge: 18,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'UPGRADE15',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid on selected items only.',
      businessIndustry: 'Automotive Services',
      businessCategories: ['Auto Accessories'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Car+Accessories!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '50',
      businessProfile: null,
      categories: ['Shopping'],
      title: 'Save $50 on Custom Paint Jobs!',
      keywords: ['customization', 'paint job', 'auto services'],
      description:
        'Make your car stand out with a custom paint job and save $50 this week.',
      minTargetAge: 21,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'PAINT50',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for standard color options only.',
      businessIndustry: 'Automotive Services',
      businessCategories: ['Customization'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Custom+Paint+Jobs!.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '25',
      businessProfile: null,
      categories: ['Shopping'],
      title: 'Get a $25 Off Premium Car Detailing!',
      keywords: ['detailing', 'car wash', 'premium service'],
      description:
        'Bring back the shine with our premium detailing service. Save $25 this month!',
      minTargetAge: 18,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'DETAIL25',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for full detailing packages only.',
      businessIndustry: 'Automotive Services',
      businessCategories: ['Detailing'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Car+Accessories!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },

    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '20',
      businessProfile: null,
      categories: ['Entertainment'],
      title: '20% Off Weekend Passes!',
      keywords: ['amusement', 'family fun', 'discount'],
      description:
        'Enjoy 20% off weekend passes at our amusement center! Fun for the whole family.',
      minTargetAge: 10,
      maxTargetAge: 50,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'WEEKENDFUN',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid on Saturdays and Sundays only.',
      businessIndustry: 'Entertainment',
      businessCategories: ['Amusement Center'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Event+Planning+Packages!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '30',
      businessProfile: null,
      categories: ['Entertainment'],
      title: '$30 Off Group Bookings!',
      keywords: ['escape room', 'group activity', 'discount'],
      description:
        'Book an escape room experience for 4 or more people and save $30!',
      minTargetAge: 16,
      maxTargetAge: 45,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'ESCAPE30',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid on bookings of 4 or more. Excludes holidays.',
      businessIndustry: 'Entertainment',
      businessCategories: ['Escape Room'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Group+Bookings!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '10',
      businessProfile: null,
      categories: ['Entertainment'],
      title: '10% Off Event Planning Packages!',
      keywords: ['event planning', 'party', 'discount'],
      description:
        'Plan your next big event with us and get 10% off any package!',
      minTargetAge: 25,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'PLAN10',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Offer valid for bookings made this month.',
      businessIndustry: 'Entertainment',
      businessCategories: ['Event Planning'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Event+Planning+Packages!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '25',
      businessProfile: null,
      categories: ['Clubs'],
      title: '25% Off First Dance Class!',
      keywords: ['dance studio', 'dance classes', 'discount'],
      description:
        'Join our dance studio and get 25% off your first class! Perfect for beginners.',
      minTargetAge: 12,
      maxTargetAge: 50,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'DANCE25',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'New members only. Valid for first class.',
      businessIndustry: 'Fitness & Wellness',
      businessCategories: ['Dance Studio'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/First+Dance+Class!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '20',
      businessProfile: null,
      categories: ['Clubs'],
      title: 'Save $20 on Monthly Membership!',
      keywords: ['fitness center', 'gym', 'membership'],
      description:
        'Get fit with us! Enjoy a $20 discount on your first month of membership.',
      minTargetAge: 18,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'FIT20',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for new memberships only.',
      businessIndustry: 'Fitness & Wellness',
      businessCategories: ['Fitness Center'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Monthly+Membership!+.jpeg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '15',
      businessProfile: null,
      categories: ['Clubs'],
      title: '15% Off All Yoga Classes!',
      keywords: ['yoga', 'wellness', 'discount'],
      description:
        'Experience tranquility and balance with 15% off all yoga classes this month.',
      minTargetAge: 18,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'ZEN15',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid on drop-in classes only.',
      businessIndustry: 'Fitness & Wellness',
      businessCategories: ['Yoga Studio'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Yoga+Classes!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '30',
      businessProfile: null,
      categories: ['Attractions'],
      title: 'Save $30 on Appliance Repair!',
      keywords: ['appliance repair', 'home services', 'discount'],
      description:
        'Get $30 off your first appliance repair service. Fast and reliable fixes!',
      minTargetAge: 25,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'FIX30',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions:
        'Valid for first-time customers only. Excludes parts.',
      businessIndustry: 'Home Services',
      businessCategories: ['Appliance Repair'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Appliance+Repair!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '20',
      businessProfile: null,
      categories: ['Attractions'],
      title: '20% Off Deep Cleaning Package!',
      keywords: ['home cleaning', 'deep clean', 'discount'],
      description:
        'Freshen up your home with 20% off our deep cleaning package. Book today!',
      minTargetAge: 25,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'CLEAN20',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Offer valid for full home cleaning packages only.',
      businessIndustry: 'Home Services',
      businessCategories: ['Home Cleaning'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Deep+Cleaning+Package!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '50',
      businessProfile: null,
      categories: ['Attractions'],
      title: '$50 Off Emergency Plumbing!',
      keywords: ['plumbing services', 'emergency plumbing', 'discount'],
      description:
        'Need urgent plumbing help? Get $50 off any emergency service today.',
      minTargetAge: 25,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'PLUMB50',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for emergency calls only. Excludes materials.',
      businessIndustry: 'Home Services',
      businessCategories: ['Plumbing Services'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Emergency+Plumbing!+.png',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '15',
      businessProfile: null,
      categories: ['Attractions'],
      title: '15% Off Weekend Stays!',
      keywords: ['bed & breakfast', 'hospitality', 'discount', 'weekend'],
      description:
        'Escape the city and enjoy a cozy weekend at our B&B with 15% off your stay.',
      minTargetAge: 25,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'RELAX15',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for Friday to Sunday stays. Booking required.',
      businessIndustry: 'Hospitality',
      businessCategories: ['Bed & Breakfast'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Weekend+Stays!+.png',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '50',
      businessProfile: null,
      categories: ['Attractions'],
      title: '$50 Off Your Next Booking!',
      keywords: ['hotel', 'stay', 'discount', 'booking'],
      description:
        'Book your next hotel stay with us and save $50 on any room category.',
      minTargetAge: 18,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'STAY50',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Offer valid on bookings of 2 nights or more.',
      businessIndustry: 'Hospitality',
      businessCategories: ['Hotel'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Weekend+Stays!+.png',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '20',
      businessProfile: null,
      categories: ['Attractions'],
      title: '20% Off Long Stays!',
      keywords: ['vacation rentals', 'hospitality', 'discount', 'long stay'],
      description:
        'Planning an extended getaway? Get 20% off vacation rentals when you book for 7 nights or more.',
      minTargetAge: 21,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'LONGSTAY20',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for stays of 7 nights or longer.',
      businessIndustry: 'Hospitality',
      businessCategories: ['Vacation Rentals'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Long+Stays!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '20',
      businessProfile: null,
      categories: ['Pets'],
      title: '20% Off Grooming Packages!',
      keywords: ['pet grooming', 'discount', 'dog grooming', 'cat grooming'],
      description:
        'Pamper your pet with a grooming session and enjoy 20% off any package!',
      minTargetAge: 18,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'GROOM20',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions:
        'Valid on full grooming packages only. Appointment required.',
      businessIndustry: 'Pet Services',
      businessCategories: ['Pet Grooming'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Grooming+Packages!+.jpeg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '15',
      businessProfile: null,
      categories: ['Pets'],
      title: '$15 Off Weekend Boarding!',
      keywords: ['pet boarding', 'pet care', 'weekend discount'],
      description:
        'Going away for the weekend? Book your pet’s stay and get $15 off!',
      minTargetAge: 25,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'BOARD15',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for weekend stays only. Limited availability.',
      businessIndustry: 'Pet Services',
      businessCategories: ['Pet Boarding'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Weekend+Boarding!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '10',
      businessProfile: null,
      categories: ['Pets'],
      title: '10% Off First Vet Visit!',
      keywords: ['veterinary clinic', 'pet care', 'discount', 'first visit'],
      description:
        'New to our clinic? Get 10% off your pet’s first consultation with us.',
      minTargetAge: 18,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'HEALTHY10',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for new patients only. Appointment required.',
      businessIndustry: 'Pet Services',
      businessCategories: ['Veterinary Clinic'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/First+Vet+Visit!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '20',
      businessProfile: null,
      categories: ['Pets'],
      title: '20% Off Grooming Packages!',
      keywords: ['pet grooming', 'discount', 'dog grooming', 'cat grooming'],
      description:
        'Pamper your pet with a grooming session and enjoy 20% off any package!',
      minTargetAge: 18,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'GROOM20',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions:
        'Valid on full grooming packages only. Appointment required.',
      businessIndustry: 'Pet Services',
      businessCategories: ['Pet Grooming'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Grooming+Packages!+.jpeg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '15',
      businessProfile: null,
      categories: ['Pets'],
      title: '$15 Off Weekend Boarding!',
      keywords: ['pet boarding', 'pet care', 'weekend discount'],
      description:
        'Going away for the weekend? Book your pet’s stay and get $15 off!',
      minTargetAge: 25,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'BOARD15',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for weekend stays only. Limited availability.',
      businessIndustry: 'Pet Services',
      businessCategories: ['Pet Boarding'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Weekend+Boarding!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '10',
      businessProfile: null,
      categories: ['Pets'],
      title: '10% Off First Vet Visit!',
      keywords: ['veterinary clinic', 'pet care', 'discount', 'first visit'],
      description:
        'New to our clinic? Get 10% off your pet’s first consultation with us.',
      minTargetAge: 18,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'HEALTHY10',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Valid for new patients only. Appointment required.',
      businessIndustry: 'Pet Services',
      businessCategories: ['Veterinary Clinic'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/First+Vet+Visit!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '20',
      businessProfile: null,
      categories: ['Shopping'],
      title: '20% Off Tax Consultation!',
      keywords: ['accounting', 'tax', 'consulting', 'discount'],
      description:
        'Get 20% off your first tax consultation with our certified accounting experts.',
      minTargetAge: 25,
      maxTargetAge: 60,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'TAX20',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions:
        'Valid for first-time clients only. Appointment required.',
      businessIndustry: 'Professional Services',
      businessCategories: ['Accounting Consultant'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Tax+Consultation!+.png',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'FLAT',
      discountValue: '50',
      businessProfile: null,
      categories: ['Shopping'],
      title: '$50 Off Business Strategy Session!',
      keywords: ['business consulting', 'strategy', 'discount'],
      description:
        'Enhance your business strategy with a $50 discount on our expert consultation session.',
      minTargetAge: 30,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'BIZ50',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Offer valid for the first session only.',
      businessIndustry: 'Professional Services',
      businessCategories: ['Business Consultant'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Business+Strategy+Session!+.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    {
      creatorType: 'AdminUser',
      type: 'offer',
      user: null,
      discountType: 'PERCENTAGE',
      discountValue: '15',
      businessProfile: null,
      categories: ['Shopping'],
      title: '15% Off Legal Consultation!',
      keywords: ['legal services', 'lawyer', 'consultation', 'discount'],
      description:
        'Book a legal consultation today and get 15% off your first session with our attorneys.',
      minTargetAge: 25,
      maxTargetAge: 65,
      targetGenders: ['male', 'female', 'others'],
      promotionCode: 'LEGAL15',
      isFree: false,
      participationCost: '',
      termsApplied: true,
      termsAndConditions: 'Offer valid for initial consultations only.',
      businessIndustry: 'Professional Services',
      businessCategories: ['Legal Services'],
      thumbnail:
        'https://pinntag-assets.s3.us-east-1.amazonaws.com/Templates/Legal+Consultation!.jpg',
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
  ],

  DashboardConfigs: [
    {
      name: 'Trending Now',
      offersIncluded: true,
      eventsIncluded: true,
      flashOffersIncluded: true,
      freeIncluded: true,
      limit: 7,
      categories: ['Entertainment', 'Nightlife', 'Sports', 'Dining', 'Fitness'],
      sortOrder: 100,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Flash Deals',
      offersIncluded: false,
      eventsIncluded: false,
      flashOffersIncluded: true,
      freeIncluded: true,
      limit: 7,
      categories: ['Dining', 'Shopping', 'Grooming', 'Happy Hour'],
      sortOrder: 200,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Free Offers',
      offersIncluded: true,
      eventsIncluded: true,
      flashOffersIncluded: false,
      freeIncluded: true,
      limit: 7,
      categories: [
        'Clubs',
        'Days Out',
        'Entertainment',
        'Attractions',
        'Charity',
      ],
      sortOrder: 300,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Food and Drinks',
      offersIncluded: true,
      eventsIncluded: true,
      flashOffersIncluded: false,
      freeIncluded: true,
      limit: 7,
      categories: ['Dining', 'Happy Hour'],
      sortOrder: 400,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Events Near You',
      offersIncluded: false,
      eventsIncluded: true,
      flashOffersIncluded: false,
      freeIncluded: true,
      limit: 7,
      categories: ['Nightlife', 'Sports', 'Attractions', 'Entertainment'],
      sortOrder: 500,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Health and Wellness',
      offersIncluded: true,
      eventsIncluded: true,
      flashOffersIncluded: false,
      freeIncluded: true,
      limit: 7,
      categories: ['Fitness', 'Clubs'],
      sortOrder: 600,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Charity and Community',
      offersIncluded: true,
      eventsIncluded: true,
      flashOffersIncluded: false,
      freeIncluded: true,
      limit: 7,
      categories: ['Charity', 'Attractions'],
      sortOrder: 700,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Nightlife and Parties',
      offersIncluded: true,
      eventsIncluded: true,
      flashOffersIncluded: false,
      freeIncluded: true,
      limit: 7,
      categories: ['Nightlife', 'Happy Hour'],
      sortOrder: 800,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Retail and Shopping',
      offersIncluded: true,
      eventsIncluded: false,
      flashOffersIncluded: false,
      freeIncluded: true,
      limit: 7,
      categories: ['Shopping'],
      sortOrder: 900,
      carouselType: CarouselType.Event,
    },
    {
      name: 'Pet Friendly',
      offersIncluded: true,
      eventsIncluded: true,
      flashOffersIncluded: false,
      freeIncluded: true,
      limit: 7,
      categories: ['Pets'],
      sortOrder: 1000,
      carouselType: CarouselType.Event,
    },
  ],
  DashboardBusinessConfigs: [
    {
      name: 'Popular in Atlanta',
      limit: 10,
      businessIndustries: [
        BusinessIndustries.FOOD_DRINK,
        BusinessIndustries.ENTERTAINMENT,
      ],
      sortOrder: 10,
      carouselType: CarouselType.Business,
    },
    {
      name: 'Black-Owned in ATL',
      limit: 8,
      businessIndustries: [
        BusinessIndustries.RETAIL,
        BusinessIndustries.HEALTH_BEAUTY,
      ],
      sortOrder: 20,
      carouselType: CarouselType.Business,
    },
    {
      name: 'Wellness in Midtown',
      limit: 7,
      businessIndustries: [
        BusinessIndustries.FITNESS_WELLNESS,
        BusinessIndustries.HEALTH_BEAUTY,
      ],
      sortOrder: 30,
      carouselType: CarouselType.Business,
    },
    {
      name: 'Pet-Friendly Spots',
      limit: 6,
      businessIndustries: [BusinessIndustries.PET_SERVICES],
      sortOrder: 40,
      carouselType: CarouselType.Business,
    },
    {
      name: 'Southern Comfort Food',
      limit: 5,
      businessIndustries: [BusinessIndustries.FOOD_DRINK],
      sortOrder: 50,
      carouselType: CarouselType.Business,
    },
    {
      name: 'Home Services in Buckhead',
      limit: 6,
      businessIndustries: [BusinessIndustries.HOME_SERVICES],
      sortOrder: 60,
      carouselType: CarouselType.Business,
    },
    {
      name: 'Date Night Favorites',
      limit: 7,
      businessIndustries: [
        BusinessIndustries.ENTERTAINMENT,
        BusinessIndustries.HOSPITALITY,
      ],
      sortOrder: 70,
      carouselType: CarouselType.Business,
    },
    {
      name: 'Car Care in ATL',
      limit: 6,
      businessIndustries: [BusinessIndustries.AUTOMOTIVE_SERVICES],
      sortOrder: 80,
      carouselType: CarouselType.Business,
    },
    {
      name: 'Trusted Local Pros',
      limit: 8,
      businessIndustries: [BusinessIndustries.PROFESSIONAL_SERVICES],
      sortOrder: 90,
      carouselType: CarouselType.Business,
    },
    {
      name: 'ATL Events This Week',
      limit: 10,
      businessIndustries: [],
      sortOrder: 100,
      carouselType: CarouselType.Business,
    },
  ],
  Departments: [
    {
      name: 'Operations',
      description: 'Manages day-to-day business operations.',
      roles: [
        'Store Manager',
        'General Manager',
        'Regional Manager',
        'Operational Manager',
      ],
    },
    {
      name: 'Marketing',
      description:
        'Responsible for promoting products and enhancing brand image.',
      roles: ['Marketing Manager'],
    },
    {
      name: 'Finance',
      description: 'Handles financial transactions, reporting, and budgeting.',
      roles: ['Finance Manager'],
    },
    {
      name: 'Customer Support',
      description: 'Provides assistance and support to customers.',
      roles: ['Support Executive'],
    },
    {
      name: 'Sales',
      description: 'Drives revenue through customer acquisition and retention.',
      roles: ['Regional Manager', 'General Manager', 'Store Manager'],
    },
    {
      name: 'Product Management',
      description: 'Responsible for product planning and development.',
      roles: ['Operational Manager', 'General Manager'],
    },
    {
      name: 'Human Resources',
      description:
        'Manages recruitment, employee relations, and personnel policies.',
      roles: ['General Manager'],
    },
    {
      name: 'Logistics',
      description:
        'Oversees supply chain, inventory, and product distribution.',
      roles: ['Store Manager', 'Operational Manager'],
    },
    {
      name: 'IT and Systems',
      description:
        'Manages IT infrastructure, software, and technical support.',
      roles: ['Operational Manager', 'Support Executive'],
    },
    {
      name: 'Quality Assurance',
      description:
        'Ensures product and service quality through testing and evaluation.',
      roles: ['Operational Manager', 'General Manager'],
    },
    {
      name: 'Legal and Compliance',
      description:
        'Ensures adherence to legal regulations and compliance standards.',
      roles: ['Finance Manager', 'General Manager'],
    },
  ],
  Regions: [
    {
      name: 'North',
      description: 'Covers the northern part of the country or service area.',
    },
    {
      name: 'South',
      description: 'Covers the southern part of the country or service area.',
    },
    {
      name: 'East',
      description: 'Covers the eastern part of the country or service area.',
    },
    {
      name: 'West',
      description: 'Covers the western part of the country or service area.',
    },
    {
      name: 'Central',
      description: 'Covers the central or downtown region.',
    },
  ],
};

export const BusinessIndustryTags = {
  'Food & Drink': [
    'burger',
    'pizza',
    'coffee',
    'cocktail',
    'dessert',
    'sushi',
    'happy hour',
    'brunch',
    'vegan',
    'fine dining',
    'street food',
    'brewery',
    'bar',
    'snacks',
    'grill',
    'buffet',
    'food truck',
    'smoothie',
    'mocktail',
    'ice cream',
  ],
  Retail: [
    'clothing',
    'electronics',
    'furniture',
    'shoes',
    'handbags',
    'accessories',
    'fashion',
    'home decor',
    'discount',
    'sale',
    'boutique',
    'gift shop',
    'books',
    'gadgets',
    'thrift',
    'appliances',
    'jewelry',
    'toys',
    'sportswear',
    'eyewear',
  ],
  'Health & Beauty': [
    'spa',
    'salon',
    'massage',
    'skincare',
    'nail art',
    'makeup',
    'haircut',
    'facial',
    'laser',
    'waxing',
    'botox',
    'cosmetics',
    'dermatology',
    'aromatherapy',
    'anti-aging',
    'beauty products',
    'hair color',
    'eyelash',
    'threading',
    'bridal makeover',
  ],
  'Fitness & Wellness': [
    'gym',
    'yoga',
    'meditation',
    'personal training',
    'pilates',
    'zumba',
    'wellness center',
    'weight loss',
    'health coaching',
    'fitness classes',
    'bootcamp',
    'aerobics',
    'crossfit',
    'nutrition',
    'supplements',
    'stretching',
    'cycling',
    'HIIT',
    'strength training',
    'balance training',
  ],
  Entertainment: [
    'movies',
    'karaoke',
    'arcade',
    'live music',
    'nightclub',
    'stand-up comedy',
    'escape room',
    'bowling',
    'laser tag',
    'game zone',
    'concert',
    'exhibition',
    'virtual reality',
    'drama',
    'billiards',
    'festival',
    'dance',
    'trivia night',
    'DJ',
    'open mic',
  ],
  'Automotive Services': [
    'car wash',
    'oil change',
    'repair',
    'detailing',
    'tire service',
    'auto parts',
    'battery replacement',
    'car rental',
    'mechanic',
    'alignment',
    'inspection',
    'towing',
    'windshield',
    'car insurance',
    'bike service',
    'paint service',
    'body shop',
    'auto glass',
    'engine diagnostics',
    'emissions test',
  ],
  'Home Services': [
    'plumbing',
    'electrical',
    'pest control',
    'cleaning',
    'carpentry',
    'painting',
    'landscaping',
    'AC repair',
    'appliance repair',
    'interior design',
    'security systems',
    'home automation',
    'handyman',
    'roofing',
    'flooring',
    'window cleaning',
    'gardening',
    'waterproofing',
    'furniture assembly',
    'deep cleaning',
  ],
  'Pet Services': [
    'grooming',
    'vet',
    'boarding',
    'pet food',
    'pet accessories',
    'dog walking',
    'training',
    'adoption',
    'pet spa',
    'vaccination',
    'neutering',
    'pet sitting',
    'pet store',
    'aquarium',
    'pet taxi',
    'flea control',
    'pet daycare',
    'animal hospital',
    'pet ID tag',
    'pet insurance',
  ],
  Hospitality: [
    'hotel',
    'motel',
    'resort',
    'bnb',
    'hostel',
    'room service',
    'concierge',
    'luxury stay',
    'suite',
    'accommodation',
    'vacation rental',
    'guest house',
    'check-in',
    'check-out',
    'booking',
    'staycation',
    'hospitality service',
    'valet',
    'banquet',
    'lodging',
  ],
  'Professional Services': [
    'consulting',
    'legal',
    'accounting',
    'marketing',
    'IT services',
    'design',
    'photography',
    'translation',
    'tax services',
    'recruitment',
    'tutoring',
    'architecture',
    'engineering',
    'editing',
    'content writing',
    'business coaching',
    'HR services',
    'financial planning',
    'event planning',
    'copywriting',
  ],
};

export const ContentTags = {
  Art: [
    'gallery',
    'exhibition',
    'painting',
    'sculpture',
    'art class',
    'mural',
    'installation',
    'craft fair',
    'art studio',
    'sketching',
    'digital art',
    'art supplies',
    'open studio',
    'art market',
    'calligraphy',
    'pottery',
    'photography',
    'mixed media',
    'art walk',
    'art auction',
  ],
  Grooming: [
    'salon',
    'barber',
    'haircut',
    'beard trim',
    'shave',
    'styling',
    'facial',
    'waxing',
    'spa',
    'nail salon',
    'manicure',
    'pedicure',
    'hair spa',
    'makeover',
    'bridal grooming',
    'threading',
    'eyebrow',
    'scalp treatment',
    "men's grooming",
    'beauty service',
  ],
  Charity: [
    'fundraiser',
    'donation drive',
    'volunteering',
    'nonprofit',
    'community event',
    'clothing drive',
    'blood donation',
    'relief fund',
    'charity auction',
    'sponsorship',
    'support group',
    'ngo',
    'food drive',
    'awareness campaign',
    'animal rescue',
    'green initiative',
    'education support',
    'healthcare aid',
    'disaster relief',
    'crowdfunding',
  ],
  Clubs: [
    'nightclub',
    'music club',
    'dance floor',
    'DJ night',
    'exclusive entry',
    'bottle service',
    'club party',
    'members only',
    'theme night',
    'VIP lounge',
    'hookah lounge',
    'electronic music',
    'club event',
    'afterparty',
    'bar crawl',
    'clubwear',
    'party pass',
    'ladies night',
    'guest list',
    'club dance',
  ],
  'Days Out': [
    'picnic',
    'zoo',
    'amusement park',
    'museum',
    'boat ride',
    'day trip',
    'nature trail',
    'beach',
    'aquarium',
    'park',
    'historical site',
    'local tour',
    'hiking',
    'outdoor fun',
    'camping',
    'road trip',
    'bike ride',
    'adventure park',
    'water park',
    'garden',
  ],
  Entertainment: [
    'movies',
    'theatre',
    'live music',
    'comedy show',
    'magic show',
    'dance show',
    'gaming',
    'concert',
    'cultural fest',
    'virtual reality',
    'arcade',
    'laser tag',
    'escape room',
    'open mic',
    'talent show',
    'DJ',
    'trivia night',
    'karaoke',
    'cinema',
    'festival',
  ],
  Dining: [
    'restaurant',
    'fine dining',
    'casual dining',
    'food court',
    'buffet',
    'brunch',
    'family dining',
    'open terrace',
    'food tasting',
    'chef special',
    'outdoor dining',
    'multi-cuisine',
    'dine-in',
    'table reservation',
    'live kitchen',
    'tandoor',
    'fusion food',
    'gourmet',
    'street food',
    'rooftop',
  ],
  'Happy Hour': [
    'discounted drinks',
    'buy one get one',
    'cocktail deal',
    'beer special',
    '2-for-1',
    'evening offer',
    'bar promo',
    'wine offer',
    'snack combo',
    'late night happy hour',
    'limited time',
    'alcohol deal',
    'mocktail offer',
    'liquor discount',
    'mixology',
    'draft beer',
    'spirit special',
    'weekday offer',
    'drink and dine',
    'pub deal',
  ],
  Fitness: [
    'gym',
    'yoga',
    'zumba',
    'HIIT',
    'bootcamp',
    'personal training',
    'aerobics',
    'cycling',
    'strength training',
    'pilates',
    'stretching',
    'martial arts',
    'crossfit',
    'bodyweight',
    'outdoor run',
    'fitness challenge',
    'dance workout',
    'step training',
    'core workout',
    'group class',
  ],
  Attractions: [
    'theme park',
    'zoo',
    'aquarium',
    'landmark',
    'scenic point',
    'botanical garden',
    'cable car',
    'observation deck',
    'tourist spot',
    'historical site',
    'fountain',
    'museum',
    'art gallery',
    'monument',
    'palace',
    'fort',
    'adventure park',
    'castle',
    'lakefront',
    'cultural attraction',
  ],
  Nightlife: [
    'bar',
    'club',
    'live music',
    'DJ',
    'pub',
    'hookah',
    'dance floor',
    'karaoke',
    'afterparty',
    'night market',
    'night event',
    'happy hour',
    'late night snacks',
    'cocktail',
    'ladies night',
    'whiskey tasting',
    'brewpub',
    'night lounge',
    'sunset view',
    'open till late',
  ],
  Pets: [
    'grooming',
    'vet',
    'boarding',
    'pet spa',
    'dog park',
    'pet food',
    'adoption',
    'vaccination',
    'training',
    'leash',
    'pet hotel',
    'neutering',
    'accessories',
    'treats',
    'aquarium',
    'cat cafe',
    'dog show',
    'pet walk',
    'clinic',
    'animal shelter',
  ],
  Sports: [
    'football',
    'cricket',
    'basketball',
    'tennis',
    'badminton',
    'table tennis',
    'hockey',
    'golf',
    'baseball',
    'volleyball',
    'running',
    'cycling',
    'swimming',
    'martial arts',
    'kabaddi',
    'skating',
    'boxing',
    'squash',
    'e-sports',
    'athletics',
  ],
  Shopping: [
    'mall',
    'boutique',
    'fashion',
    'electronics',
    'footwear',
    'discount',
    'sale',
    'outlet',
    'market',
    'jewelry',
    'makeup',
    'grocery',
    'gift shop',
    'thrift store',
    'home decor',
    'accessories',
    'apparel',
    'online deals',
    'bags',
    'luxury shopping',
  ],
};
